### ISSUE TITLE
Add list of systems with available GBFS feeds 

### ISSUE THREAD

**Issue by fkh** [MobilityData/gbfs#1]
Some SoBi systems?

**Comment by mplsmitch** [comment]
This has been hard to crack - maybe we should consider a registry that feed providers could submit systems to? Here's what I found currently (all SoBi) :

Bishop Ranch BRiteBikes 
San Ramon, CA
http://britebikes.socialbicycles.com/

Boise Green Bike
Boise, ID
http://boise.greenbike.com/

Breeze Bike Share
Sana Monica, CA
http://santamonicabikeshare.com/

Buffalo Bike Share
Buffalo, NY
https://buffalo.socialbicycles.com/

Coast Bike Share
Tampa, FL
http://coastbikeshare.com/

Grid Bike Share
Phoenix, AZ
http://gridbikes.com/

Bike Share Jackson Hole 
Jackson Hole, WY
https://jacksonhole.socialbicycles.com/

Juice
Orlando Florida
https://orlando.socialbicycles.com/

Monash Bike Share
Monash University, Melbourne AU
https://monashbikeshare.com/

Mountain Ride Bike Share
Ketchum / Sun Valley, ID
http://mrbikeshare.org/

Sobi Hamilton
Hamilton Ontario
https://hamilton.socialbicycles.com/

Sobi Long Beach
Long Beach, CA
http://sobilongbeach.com/

Topeka Metro Bikes
Topeka, KS
http://topekametrobikes.org/

Ubike
University of Virginia
http://ubike.virginia.edu/

Share-a-Bull Bikes
University of South Florida
https://usf.socialbicycles.com/

**Comment by jcn** [comment]
I think the thing that makes the most sense would be to just have a file that contains the name, system url and possibly auto-discovery url for every system that implements GBFS. As systems implemented GBFS, they could issue a pull request adding themselves, thus acting as the registry that @mplsmitch described.

**Comment by bcbeta** [comment]
Denver Bcycle referred me to NABSA for their data feed since their old api no longer seems to work for my app.  Unfortunately, there doesn't seem to be any info on the NABSA website aside from the press release.  I second the suggestion by @jcn .

**Comment by mplsmitch** [comment]
@davem2020 NABSA has nothing to do with the distribution of data, only development of the feed specification. You can find all the Denver files by looking in the head section of the their homepage for the auto-discovery link - 
<link rel='gbfs' type='application/json' href='https://gbfs.bcycle.com/bcycle_denver/gbfs.json' />

Here's the full story from Bcycle:   https://www.bcycle.com/gbfs

**Comment by bcbeta** [comment]
@mplsmitch thanks, that's what I was looking for!

**Comment by fruminator** [comment]
@jcn @fkh @davem2020 @mplsmitch why not make JCN's file be a CSV file hosted in this repo?

**Comment by dierkp** [comment]
{
                    "title": 'Denver B-cycle',
                    "lat": '39.740112',
                    "lng": '-104.9848',
                    "url": 'denver.bcycle.com'
                }
            ,
                {
                    "title": 'Des Moines B-cycle',
                    "lat": '41.58778',
                    "lng": '-93.625488',
                    "url": 'desmoines.bcycle.com'
                }
            ,
                {
                    "title": 'San Antonio B-cycle',
                    "lat": '29.425843',
                    "lng": '-98.493633',
                    "url": 'sanantonio.bcycle.com'
                }
            ,
                {
                    "title": 'Broward B-cycle',
                    "lat": '26.134851',
                    "lng": '-80.167465',
                    "url": 'broward.bcycle.com'
                }
            ,
                {
                    "title": 'Boulder B-cycle',
                    "lat": '40.020042',
                    "lng": '-105.269718',
                    "url": 'boulder.bcycle.com'
                }
            ,
                {
                    "title": 'Madison B-cycle',
                    "lat": '43.073277',
                    "lng": '-89.40176',
                    "url": 'madison.bcycle.com'
                }
            ,
                {
                    "title": 'Heartland B-cycle',
                    "lat": '41.260811',
                    "lng": '-95.952956',
                    "url": 'heartland.bcycle.com'
                }
            ,
                {
                    "title": 'Spartanburg BCycle',
                    "lat": '34.946516',
                    "lng": '-81.93031',
                    "url": 'spartanburg.bcycle.com'
                }
            ,
                {
                    "title": 'Houston B-cycle',
                    "lat": '29.762887',
                    "lng": '-95.356865',
                    "url": 'houston.bcycle.com'
                }
            ,
                {
                    "title": 'Charlotte B-cycle',
                    "lat": '35.2269',
                    "lng": '-80.8433',
                    "url": 'charlotte.bcycle.com'
                }
            ,
                {
                    "title": 'Kansas City B-cycle',
                    "lat": '39.071066',
                    "lng": '-94.585287',
                    "url": 'kc.bcycle.com'
                }
            ,
                {
                    "title": 'Nashville B-cycle',
                    "lat": '36.167578',
                    "lng": '-86.762172',
                    "url": 'nashville.bcycle.com'
                }
            ,
                {
                    "title": 'Greenville B-cycle',
                    "lat": '34.8525',
                    "lng": '-82.3942',
                    "url": 'greenville.bcycle.com'
                }
            ,
                {
                    "title": 'GREENbike',
                    "lat": '40.767087',
                    "lng": '-111.891074',
                    "url": 'www.greenbikeslc.org'
                }
            ,
                {
                    "title": 'Fort Worth Bike Sharing',
                    "lat": '32.736028',
                    "lng": '-97.340755',
                    "url": 'fortworth.bcycle.com'
                }
            ,
                {
                    "title": 'Bike Santiago',
                    "lat": '-33.389528',
                    "lng": '-70.568018',
                    "url": 'www.bikesantiago.cl'
                }
            ,
                {
                    "title": 'Bublr Bikes',
                    "lat": '43.037278',
                    "lng": '-87.914081',
                    "url": 'bublrbikes.com'
                }
            ,
                {
                    "title": 'Battle Creek B-cycle',
                    "lat": '42.3211',
                    "lng": '-85.1797',
                    "url": 'battlecreek.bcycle.com'
                }
            ,
                {
                    "title": 'Austin B-cycle',
                    "lat": '30.262477',
                    "lng": '-97.746906',
                    "url": 'austinbcycle.com'
                }
            ,
                {
                    "title": 'Savannah',
                    "lat": '32.080902',
                    "lng": '-81.097605',
                    "url": 'catbike.bcycle.com'
                }
            ,
                {
                    "title": 'Columbia County B-cycle',
                    "lat": '33.543376',
                    "lng": '-82.131325',
                    "url": 'columbiacounty.bcycle.com'
                }
            ,
                {
                    "title": 'Indy - Pacers Bikeshare ',
                    "lat": '39.770565',
                    "lng": '-86.159272',
                    "url": 'pacersbikeshare.org'
                }
            ,
                {
                    "title": 'ArborBike',
                    "lat": '42.280524',
                    "lng": '-83.738929',
                    "url": 'arborbike.org'
                }
            ,
                {
                    "title": 'Rapid City B-cycle',
                    "lat": '44.076',
                    "lng": '-103.22',
                    "url": 'rapidcity.bcycle.com'
                }
            ,
                {
                    "title": 'Cincy Red Bike',
                    "lat": '39.120027',
                    "lng": '-84.515511',
                    "url": 'cincyredbike.org'
                }
            ,
                {
                    "title": 'Great Rides Bike Share',
                    "lat": '46.887902',
                    "lng": '-96.794589',
                    "url": 'greatrides.bcycle.com'
                }
            ,
                {
                    "title": 'Link Dayton Bike Share',
                    "lat": '39.749501',
                    "lng": '-84.186559',
                    "url": 'www.linkdayton.org'
                }
            ,
                {
                    "title": 'El Paso B-cycle',
                    "lat": '31.764567',
                    "lng": '-106.492821',
                    "url": 'elpaso.bcycle.com'
                }
            ,
                {
                    "title": 'McAllen B-cycle',
                    "lat": '26.208426',
                    "lng": '-98.242907',
                    "url": 'mcallen.bcycle.com'
                }
            ,
                {
                    "title": 'Clarksville B-cycle',
                    "lat": '36.520804',
                    "lng": '-87.348289',
                    "url": 'clarksville.bcycle.com'
                }
            ,
                {
                    "title": 'Indego',
                    "lat": '39.958241',
                    "lng": '-75.165737',
                    "url": 'www.rideindego.com'
                }

**Comment by jcn** [comment]
> @jcn @fkh @davem2020 @mplsmitch why not make JCN's file be a CSV file hosted in this repo?

I took a first pass at what this CSV might look like using @mplsmitch's initial list. Happy to entertain comments: https://github.com/NABSA/gbfs/pull/17

**Comment by jcn** [comment]
> {
> "title": 'Denver B-cycle',
> "lat": '39.740112',
> "lng": '-104.9848',
> "url": 'denver.bcycle.com'
> }
> ...

@dierkp Please submit a pull request to add these BCycle systems to the https://github.com/NABSA/gbfs/blob/master/systems.csv file.
