### ISSUE TITLE
Change boolean values from 1/0 to true/false

### ISSUE THREAD

**Issue by jcn** [MobilityData/gbfs#10]
A proposal from Tom Brown in the original draft:

> "boolean" suggests true/false to me, but it looks like you want int number 0 or 1. if you think this may become 3 or more state an enum string may be clearer. if it you expect it to remain binary json true/false looks like a good fit.

The integers 0 and 1 evaluate as falsy and truthy in Javascript but not in other languages so converting these to true booleans would make these values more explicit. They would represent an additional several characters in the underlying file, which may or may not be a concern from a bandwidth perspective, but it's the only reason I could think to not make this change.

**Comment by fruminator** [comment]
I like Boolean.

**Comment by dsgermain** [comment]
Agree with this one as well. BTW, I'm the director of engineering at PBSC, pleasure to meet you all.

**Comment by jasongdove** [comment]
I like true/false.

**Comment by andmos** [comment]
Might be late to the party, but as a writer of client library that uses the GBFS standard, avoiding special handling of the bool types would be nice.

**Comment by heidiguenin** [comment]
Hey all! Now that we're actually moving toward a versioning scheme and then likely making use of it right away with #147, I'd like to suggest we bundle up a few other small breaking changes, including this one.  

Seems like we have consensus on this one. @jcn want to open a PR?

**Comment by heidiguenin** [comment]
I've opened a PR for this over at #196 - let's move any more conversation there, and I'll close this in a few days.
