### ISSUE TITLE
Ability to query data by date

### ISSUE THREAD

**Issue by asosnovsky** [MobilityData/gbfs#103]
I was thinking, wouldn't it be great to be able to query the api based on date,
for example

`https://tor.publicbikesystem.net/ube/gbfs/v1/en/station_status?startDate=1500801931187&endDate=1510801931187`

**Comment by afischer** [comment]
While past data is great, It's worth noting the introduction specifically notes the purpose of this project is _not_ to provide historical data.

Many vendors provide historical data on their sites, but the data on a GBFS feed changes frequently. Significant overhead would be required for vendors to support to-the-second histories.

**Comment by heidiguenin** [comment]
Hey @asosnovsky & @afischer - I'm going to go ahead and close this one down for now. Thanks!
