### ISSUE TITLE
Shared scooters

### ISSUE THREAD

**Issue by Dehorser** [MobilityData/gbfs#105]
Will gbfs be expanded to cover shared scooters?

**Comment by michalnaka** [comment]
Yeah I was wondering the same thing^

**Comment by mplsmitch** [comment]
There's been some discussion about how might be done in #81  - As far as I know it's already being used for scooters in some cities but I haven't found the data source, here's an example:  http://bikes.oobrien.com/washingtondcskip/#zoom=10&lon=-77.1224&lat=38.7025

**Comment by sven4all** [comment]
Would be interesting, I am working on a concrete proposal. I think it's a good idea to take scooters into account. https://github.com/openbikeshare/gbfs/blob/bike_types/gbfs.md#bike_typesjson

**Comment by heidiguenin** [comment]
Hey all! PR #136 responds to this request, please take a look and provide any comments/concerns there. Once folks have had a chance to check it out, I'd love to go ahead and close this issue.

@Dehorser @michalnaka @sven4all
