### ISSUE TITLE
add an in_use flag to help compute trips

### ISSUE THREAD

**Issue by fscottfoti** [MobilityData/gbfs#111]
This is tangentially related to #47.

We at [Populus](https://www.populus.ai/) have been working to convert GBFS feeds to trip logs.  One of the biggest issues is that when a bike disappears from the feed, we can't tell whether the bike is in use (on a trip) or if it's undergoing maintenance, being charged, etc.  Also it's hard to differentiate short trips from connectivity issues / GPS noise (i.e. did a bike move 200 meters in 3 minutes, or was that just a gust of wind).

I wonder if it would help to leave a bike which is in use in the GBFS feed with an in_use flag.  This would help address the above, and we also could know how many bikes are out there at any given time, which you can't know now.  In theory, operators could continue to include some location information for the trip even when the vehicle is in use, and we could very roughly track the trip route for infrastructure planning purposes.  

Some context here is that we are working with the cities to help them know how their bike and scooter share systems are working holistically.  I understand from the responses to #47 that this is not the purpose of GBFS exactly, but it seems to me that GBFS could evolve to support this and keep from forcing my group and others from having to overhaul the standard entirely like [MDS](https://github.com/CityOfLosAngeles/mobility-data-specification).  Any thoughts on this use case, which I think will be increasingly common in the future.  Is it better to just have the operators use MDS and report their own trips?  I know that some cities would rather use GBFS because they don't trust the operators to report their trips perfectly.

**Comment by heidiguenin** [comment]
Hey @fscottfoti - a couple of your Populus colleagues were at the GBFS developers workshop held before the NABSA 2019 conference (workshop [agenda](https://docs.google.com/document/d/13uXgMF5LWYvKX7vw5Y6_SZsBmtd32VS0opEfDJFjJYo/edit?usp=sharing) and [notes](https://docs.google.com/document/d/1TXf3U7gbrJrS_r2PmTrfbJspNydAyd42xU3ctNgzNLM/edit?usp=sharing)), where one hot topic of discussion was the roles of GBFS and MDS. While GBFS' purpose is not to support research or enforcement, we recognize that stakeholders may be using GBFS datasets to support those functions. Still, to avoid spec scope creep, we are suggesting that MDS is where this belongs. The hope is that cities will be able to use GBFS datasets as supplemental data, and in the future, GBFS validators will make this easier.  The intention is also for the GBFS and MDS stakeholder communities to work closely together in the future to make sure these kinds of cross-spec requests don't get lost.  I'm going to give this a few days and then go ahead and close out this issue.

@hunterowens @thekaveman

**Comment by yocontra** [comment]
Just wanted to note that this would be in conflict w/ https://github.com/NABSA/gbfs/pull/147
