### ISSUE TITLE
gbfs validation

### ISSUE THREAD

**Issue by PierrickP** [MobilityData/gbfs#113]
Hello,
i made a validation tool on https://github.com/PierrickP/gbfs-validator (the cli should working) and https://gbfs-validator.netlify.com/
Currently validate the current specs (1.0 ?) but i working on validate gbfs+ and futur other version.

It's a work in progress project. It could have some errors. Contribution are welcome :)

**Comment by christrillium** [comment]
Hey @PierrickP thanks for posting your validator. To further the goals of NABSA's 2019 GBFS upgrade, I'd like to include it in the [GBFS Validators section of the micromobility-tools-and resources repo](https://github.com/NABSA/micromobility-tools-and-resources#gbfs-validators). If you have any requests or suggests regarding this inclusion please let me know.

Unless you have any objections I'd like to close this issue.

**Comment by PierrickP** [comment]
@christrillium hi, no problem !
