### ISSUE TITLE
Parking regimes

### ISSUE THREAD

**Issue by sven4all** [MobilityData/gbfs#114]
I would like to develop a standard for communicating parking regimes (forbidden areas, virtual hubs) to bicycle operators. 

The reason that I think  a new standard is needed is that normally GBFS is created by bike sharing operators, while parking regimes are created by local governements. It would be more efficient if a local government shares there parking regime then having multiple operators drawing the same regime on a map themselves. Anyone interested to help me with developing this standard?

**Comment by barbeau** [comment]
@sven4all You might want to check out the [Alliance for Parking Data Standards (APDS)](https://www.allianceforparkingdatastandards.org/).

From the [awesome-transit](https://github.com/CUTR-at-USF/awesome-transit#other-multimodal-data-formats) list:

>[Alliance for Parking Data Standards (APDS)](https://www.allianceforparkingdatastandards.org/) - Formed by the [International Parking Institute (IPI)](https://www.parking.org/), the [British Parking Association (BPA)](http://www.britishparking.co.uk/), and the [European Parking Association (EPA)](http://www.europeanparking.eu/), APDS is a not-for-profit organization with the mission to develop, promote, manage, and maintain a uniform global standard that will allow organizations to share parking data across platforms worldwide.  APDS Version 1.0 documents are [here](https://www.allianceforparkingdatastandards.org/resources).

**Comment by sven4all** [comment]
I will have a look. I am not sure if it suitable for shared mobility parking regimes, but some inspiration is always helpful.

**Comment by craigmulligan** [comment]
@sven4all, I'm also interested in the concept of a virtual hub within the spec. 

We could either propose adding a new `virtual hub` or as I prefer (`parking_zone`). For my use case all we'd need is:

```
zone_id: <string>
lat: <float>
lng: <float>
geojson: <json>
num_bikes_available: <int>
```
As it stands i could use the current `station_status` to list parking zones. Is that something the current operators do?

**Comment by sven4all** [comment]
I don't know, I am proposing something similar as well in this proposal https://github.com/openbikeshare/gbfs/blob/virtual_location/gbfs.md. If you would like to implement I will make the proposal formal, so that it's in the official GBFS specification.

This proposal/ticket is really about giving governments/authorities the ability to share the parking policies with bike sharing operators. (For example prohibiting the parking of shared bicycles on a square in front of a station).

**Comment by mplsmitch** [comment]
@hobochild fields that describe a mostly static thing like station or parking zone, in your example: `zone_id` `lat`  `lon`  and `geojson` should be separated from fields that describe the current state: `num_bikes_avaialble`.  In the current version these would fall under `station_information.json` and `station_status.json` respectively. We've been publishing our virtual hub information in these two files for a while now. It's a hybrid system ( docked & dockless) - look at the IDs >210 to see the hubs
[https://gbfs.minneapolis.8d.com/gbfs/en/station_information.json](https://gbfs.minneapolis.8d.com/gbfs/en/station_information.json)
[https://gbfs.minneapolis.8d.com/gbfs/en/station_status.json](https://gbfs.minneapolis.8d.com/gbfs/en/station_status.json)

**Comment by heidiguenin** [comment]
This is similar to #167, and I'm suggesting that we close that issue and this issue out. See [my comment there](https://github.com/NABSA/gbfs/issues/167#issuecomment-539240205) and please go chime in on PR #175
