### ISSUE TITLE
ID types

### ISSUE THREAD

**Issue by PierrickP** [MobilityData/gbfs#115]
Following #113, i check all urls on `systems.csv`
Many failed because they use Int/Number instead of String for `station_id` / `bike_id`

On specs, it's written 
> ID fields in the document should be represented as strings

I understand, it should *BE* a string.
Should i consider them as errors ?

**Comment by sven4all** [comment]
Yes if it's stated like it is right now. You have to convert your integers to strings before you place them in the GBFS.

**Comment by PierrickP** [comment]
hi @sven4all 
It's what i understood.
I ll try to list all errored feeds and contact them

**Comment by heidiguenin** [comment]
Hey @PierrickP & @sven4all  - I'm going to go ahead and close this one down for now. Thanks!
