### ISSUE TITLE
Spin has Detroit and DC in same GBFS feed

### ISSUE THREAD

**Issue by brookemckim** [MobilityData/gbfs#127]
https://web.spin.pm/api/gbfs/v1/gbfs

```
{"last_updated":1543516918,"ttl":0,"data":{"en":{"feeds":[{"name":"system_information","url":"https://web.spin.pm/api/gbfs/v1/system_information"},{"name":"system_regions","url":"https://web.spin.pm/api/gbfs/v1/system_regions"},{"name":"free_bike_status","url":"https://web.spin.pm/api/gbfs/v1/detroit/free_bike_status"},{"name":"free_bike_status","url":"https://web.spin.pm/api/gbfs/v1/washington_dc/free_bike_status"}]}}}
```

@jcn does this match the spec? How should this be represented in systems.csv?

**Comment by jcn** [comment]
That's definitely not matching the spec. It looks like they are using `regions` to represent different cities, which I guess is fine, but in that case the intent is for all the data to be in one file.

Since it's fairly broken, I feel like it shouldn't be added until we can get in touch with someone from Spin to talk about what they're doing. @bennywrong perhaps you can help out or have someone from Spin chime in...

**Comment by jsierles** [comment]
Hello, I'm working on this at Spin. Just to clarify - the intent is to have a single feed for free bikes? What is meant by the title of this issue, if all regions should be represented in one feed? Thanks!

Update: I looked through existing providers like Lime who appear to split up feeds by region, each with its own discovery feed. Is that the correct implementation?

**Comment by jcn** [comment]
Hi @jsierles - yes, the intent is for each "system" (generally defined as a geographic area) to have its own discovery feed and associated data feeds. And each system should have at most one of each type of feed (i.e. it should only have a single `free_bike_status` feed).

For the existing Spin gbfs feed, I'd imagine 2 auto-discovery files: one for Detroit and one for DC, and I would probably leave out region, which is intended for systems that might have different logical distinctions in a single area (for example, a single system that might encompass multiple boroughs or towns) but for which all the data would still be served in a single feed file.

**Comment by jsierles** [comment]
Thanks for the clarification. I've made these updates. Here are the relevant URIs:

`https://web.spin.pm/api/gbfs/v1/detroit/gbfs`
`https://web.spin.pm/api/gbfs/v1/washington_dc/gbfs`
