### ISSUE TITLE
GBFS viewer webapp

### ISSUE THREAD

**Issue by idoco** [MobilityData/gbfs#134]
Hi all,

To demonstrate the importance and potential of a general feed specification, I created this tiny [GBFS viewer website](https://idoco.github.io/gbfs-viewer/). 

By agreeing on a unified feed spec, we make it possilbe to build such applications with [just 100 lines of code](https://github.com/idoco/gbfs-viewer/blob/master/index.js). 

The app reads ~all the available feeds from system.csv and displays them on a map. It is not perfect, but I'd love to get your feedback and help to improve it further. If the community finds this concept intersting, I'd be happy to transfer the repo to the @NABSA organization.

Note that some of the systems return empty feeds. If you see a problem with a system to control, let me know, and I'll try to fix it.

https://idoco.github.io/gbfs-viewer/

**Comment by mplsmitch** [comment]
Hello @idco, 
Overall I think it's great. but it looks like you're only looking at `free_bike_status.json` to populate your map so feeds from station based systems appear as empty feeds. The stations data would be in `station_information.json` & `station_status.json` . Also note that there are some hybrid systems now that have both stations and dockless bikes/scooters so all three files would be required..
 Supposing you could get the station based system feeds working maybe this could become a tool to crowd source the improvement of feed quality. In the case of broken/ incomplete or invalid feeds you could pull the contact information for the feeds owner from `system_information.json` and display it encouraging users to contact them and ask that it be improved or corrected.

**Comment by yocontra** [comment]
@mplsmitch Not sure if I've plugged this here before, but we made something similar - includes every station, bike/scooter, and trips from every bikeshare system on earth in real-time (+ lots of other open data). https://share.municipal.systems/oJl_L-B8f

Combination of crawling the GBFS systems.csv + manual imports of every trip dataset we could get our hands on (30-40 or so) + every MDS trip API.

We crawl + status check + validate everything in systems.csv on a regular basis and send PRs when they are broken for more than a day.

**Comment by idoco** [comment]
Thanks @mplsmitch, I appreciate the feedback. Getting the other feeds to work should be quite simple, I might get to it over the weekend. It is just a matter of adding another dropdown list to select from the available feeds.

I can also add information about the system from the `system_information.json`, including contact details if they exist.

**Comment by nackko** [comment]
Maybe this project can offer some inspiration as well
https://bikesharp.com

**Comment by dmah21** [comment]
Thank you for the information.

Where is information in Canada such as the following:

  *   Vancouver, British Columbia;
  *   Calgary, Alberta;
  *   Montreal, Quebec;
  *   Toronto, Ontario;
  *   Hamilton, Ontario;
  *   Ottawa, Ontario

It would be great to see at least Vancouver, Calgary, Montreal and Toronto.  Toronto has recently announced 105 new stations in a $7.5m expansion.

Deb

**Comment by christrillium** [comment]
@idoco and @contra thank you both for posting your GBFS viewers.

To further the goals of NABSA's 2019 GBFS upgrade, I'd like to include both in the[ micromobility-tools-and resources repo](https://github.com/NABSA/micromobility-tools-and-resources). If you have any requests or suggests regarding this inclusion please let me know.

Unless there are any objections I'd like to close this issue.

**Comment by christrillium** [comment]
close #134
