### ISSUE TITLE
Link issue

### ISSUE THREAD

**Issue by tanushha** [MobilityData/gbfs#142]
https://feeds.citibikenyc.com/stations/system_information.json

While I used the above link its coming Not found. So can you please tell me how to edit the link.

**Comment by jcn** [comment]
Where did you find that URL? The correct URL is listed in the [systems.csv](https://github.com/NABSA/gbfs/blob/master/systems.csv#L153) file as https://gbfs.citibikenyc.com/gbfs/en/system_information.json

**Comment by tanushha** [comment]
system_hours.json
Can you please send the link even for system_hours.json
Thank you for your quick response

**Comment by jcn** [comment]
https://gbfs.citibikenyc.com/gbfs/gbfs.json lists all of the feeds that are generated for Citi Bike. It does not look like they provide a `system_hours.json` file.

Check out the spec at https://github.com/NABSA/gbfs/blob/master/gbfs.md#files - you'll see that the `system_hours.json` file is optional.

**Comment by heidiguenin** [comment]
Hey @tanushha & @jcn, I'm going to go ahead and close this one down.
