### ISSUE TITLE
Tampa Bay GBFS feeds are in transition

### ISSUE THREAD

**Issue by barbeau** [MobilityData/gbfs#149]
For the record, GBFS in Tampa is currently...complicated.  Coast Bikeshare, currently listed as the named Tampa bikeshare operator in the systems.csv file:
https://github.com/NABSA/gbfs/blob/master/systems.csv#L160

...was originally the operator for all bikeshare in Tampa Bay, with SoBi providing the underlying technology (including GBFS feed):
http://coast.socialbicycles.com/opendata/gbfs.json

Recently, Coast Bikeshare rebranded part of the Tampa Bay deployment as operated by HOPR using their own technology, including their own GBFS feeds and mobile app.  However, part of Tampa Bay bikeshare still operates under the Coast Bikeshare brand, which uses SoBi for it's GBFS feed.  

I *believe* that the URL currently in systems.csv is still the SoBi feed, but has been restricted in scope to the St. Pete area still operated under the Coast Bikeshare brand (which seems to align with the message at the top of http://coastbikeshare.com/).

And, it seems the new HOPR feed (not currently listed in systems.csv, but proposed in https://github.com/NABSA/gbfs/pull/150) is supposed to contain the bikes for the downtown Tampa and the USF area, which are now operated under the HOPR brand with the HOPR app:
https://gbfs.hopr.city/api/gbfs/8/

Howerver, it looks like the HOPR feed is missing all Downtown Tampa stations:
https://gbfs.hopr.city/api/gbfs/8/station_information

It would be great if someone from HOPR could clarify if this is intentional or an omission - I haven't been able to get information from them when I've asked, and it's been in this state since at least mid-March.

**Comment by heidiguenin** [comment]
Test:
 @all-contributors please add @barbeau for working on getting this question answered!

**Comment by barbeau** [comment]
About a week ago HOPR added the stations back to their Tampa feed (https://github.com/NABSA/gbfs/pull/150#issuecomment-528031794), and seemed to confirm my above understanding of how the various regions in the greater Tampa Bay area will appear in the HOPR and Coast Bike Share feeds going forward.  So, I'm going to close this issue.
