### ISSUE TITLE
Show details for bikes at a station

### ISSUE THREAD

**Issue by moeffju** [MobilityData/gbfs#164]
(related to #81 discussion)

At an event where we provided shared mobility infrastructure we run a combination of dock + dockless. Currently there is no provision to show which bike(s) are at a station. This precludes use cases like “list available bikes in an app and let the user directly choose one to rent”, but also more status info such as type of “bike” (i.e. manual, electric, or a wholly different type of micromobility system such as an e-scooter) and its associated info (like charge status).

**Comment by heidiguenin** [comment]
Hey @moeffju thanks for your comment. PR #136 and #175 address this issue. Could you take a look and provide input over there?

I'd like to propose we close this issue and move relevant conversation there.
