### ISSUE TITLE
Proposal: Add city/state regulations for specific transportation options

### ISSUE THREAD

**Issue by mrmomoko** [MobilityData/gbfs#167]
First time issue creator 

I haven't thought through exactly what it would need to look like but it would be good to add local regulations regarding where and how to ride bikes in a specific location. This could be included in the system information. 

This could include needing to wear a helmet, riding on side walks, e-bike regulation in park.

**Comment by evansiroky** [comment]
I would also love to see this information be available. Since GBFS is mainly for private companies to show where their vehicles are I think there is potential for something like GBFS-for-regulators. The [MDS](https://github.com/CityOfLosAngeles/mobility-data-specification/) might end up being a place where this info could live.

**Comment by fscottfoti** [comment]
FYI https://github.com/CityOfLosAngeles/mobility-data-specification/pull/322

**Comment by heidiguenin** [comment]
Thanks @mrmomoko. I'd agree that there are two different roles here - one for MDS and one for GBFS. After the discussion at last week's workshop, are you comfortable with me closing this?

This was one issue discussed during the GBFS developers workshop held before the NABSA 2019 conference (workshop [agenda](https://docs.google.com/document/d/13uXgMF5LWYvKX7vw5Y6_SZsBmtd32VS0opEfDJFjJYo/edit?usp=sharing) and [notes](https://docs.google.com/document/d/1TXf3U7gbrJrS_r2PmTrfbJspNydAyd42xU3ctNgzNLM/edit?usp=sharing)). 

PR #175 - soon to be revised with some feedback from the workshop - should represent the way that operators provide information to travelers about regulations that impact travelers. MDS is the way for cities to push that information to operators. At the workshop, operators and regulators agreed that it is the responsibility of the operators to make sure the regulations they receive from cities are accurately shared with travelers. In the future, we hope to have validation tools that make that process easier.
