### ISSUE TITLE
Expected feed footprint: practices around multi-city/aggregated feeds?

### ISSUE THREAD

**Issue by christrillium** [MobilityData/gbfs#172]
I'm hoping to gain some insights from GBFS consumers and producers about current practices.

**Consumers:** Are you asking for or receiving multi-city aggregated feeds from producers, or are feeds generally market-specific?

**Producers:** Are consumers asking you for aggregated feeds, or are choosing to aggregate feeds for a particular reason. Or, conversely, are your feeds market specific?

Thank you!

**Comment by YngveMolnes** [comment]
> I'm hoping to gain some insights from both GBFS consumers and producers about practices around aggregated markets. This will play an important factor in future technical decisions.

I don't think i understand what is meant by aggregated feeds, is it say -- multiple systems? (e.g. a cycle hire scheme and a e-scooter scheme)

**Comment by christrillium** [comment]
By an aggregated feed, I mean multiple cities' feeds combined into one large feed. For instance, one large feed comprised of all of a particular provider's cities across the US.

**Comment by gcamp** [comment]
For Transit : feeds are generally city or market specific, and it's the way we prefer.

**Comment by kanagy** [comment]
For Maps: we get all operator data in a single feed (i.e. not a system for each city they operate in).

**Comment by antrim** [comment]
> For Maps: we get all operator data in a single feed (i.e. not a system for each city they operate in).

@kanagy Do you expect this practice to continue, and is it what you want? I'm seeing if there are parts of GBFS that should be modified to better support this.

**Comment by johnpena** [comment]
> Are consumers asking you for aggregated feeds, or are choosing to aggregate feeds for a particular reason. Or, conversely, are your feeds market specific?

For Lime: we have both market-specific feeds and aggregate feeds. I expect we'll continue to support and add new aggregate feeds.

**Comment by kanagy** [comment]
> > For Maps: we get all operator data in a single feed (i.e. not a system for each city they operate in).
> 
> @kanagy Do you expect this practice to continue, and is it what you want? I'm seeing if there are parts of GBFS that should be modified to better support this.

We'd prefer to have aggregate (global) feeds.

**Comment by christrillium** [comment]
@kanagy @johnpena @gcamp With aggregated feeds, how is the timezone field in system_information handled? Are there separate entries for each region?

**Comment by johnpena** [comment]
We've been hard-coding this value to America/Los_Angeles for aggregated feeds, since that's the time zone that Lime effectively operates in at a corporate level. I think this actually touches on a different issue, which is that for dockless, it's unclear what data `system_information` should return. We've been using it to describe Lime the company, but that might not be the intended use case.
