### ISSUE TITLE
Uses of system_regions.json?

### ISSUE THREAD

**Issue by christrillium** [MobilityData/gbfs#173]
The GTFS working group is looking for some clarity on current practices around the system_regions. 

GBFS creators and consumers, are you seeing much usage? Should we load more purposes into it, such as adding geographical information?

**Comment by heidiguenin** [comment]
During the GBFS developer's session at NABSA19, the feedback we received is that it is not being used. It was initially created to support the challenge of DC's boundaries, but DC isn't using it.

The general consensus at the workshop is to make system_regions.json optional now, with the intention to deprecate it in the future.

**Comment by mplsmitch** [comment]
I found this, not sure what purpose it serves if any: https://gbfs.capitalbikeshare.com/gbfs/en/system_regions.json

**Comment by antrim** [comment]
I created PR #183 to discuss deprecating system_regions.json.
