### ISSUE TITLE
Jump feeds reporting no free bikes

### ISSUE THREAD

**Issue by davevsdave** [MobilityData/gbfs#177]
The Jump feeds over the weekend (9/29/19) started returning zero bikes/scooters in it's free-bikes-status feed. Example: https://la.jumpbikes.com/opendata/free_bike_status.json

Anyone know what is up? 

Exceptions to this would be the newly added DC and Chicago feeds, these feeds still report free bikes.

**Comment by davevsdave** [comment]
Update on this: The free_bike_status.json for all JUMP GBFS are now removed, generating a 404, where-as before they were still live but listing zero bikes - This is true for all of the Jump feeds except for DC.

**Comment by barbeau** [comment]
Interestingly, the directory at https://la.jumpbikes.com/opendata/ still shows a listing for free_bike_status.json:

![image](https://user-images.githubusercontent.com/928045/67338917-261cd000-f4f8-11e9-9542-429cb87aabac.png)

**Comment by davevsdave** [comment]
And now that directory is down as well. I haven't been able to get any answers, but seems like Jump has decided to no longer provide data via GBFS.

**Comment by yocontra** [comment]
The LA directory is gone, I'm still getting a directory for some other cities but all of the files are gone: https://pvd.jumpbikes.com/opendata

They did just change their domain to jump.com so possibly related? Maybe the subdomain records got lost and the load balancer is still serving from cache? 🤷‍♂

**Comment by yocontra** [comment]
This seems related? Uber (Parent of JUMP) is suing to prevent the release of bike/scooter locations. Possible that they just shut this off at the same time. Source: https://www.cnet.com/news/uber-sues-los-angeles-to-keep-scooter-location-data-private/

**Comment by davevsdave** [comment]
Oh wow. For sure that's it. Nice find.

**Comment by MuteQ** [comment]
Found this link https://gbfs.uber.com/v1/laxb/gbfs.json

**Comment by davevsdave** [comment]
Also - following the same URL scheme from the DC feeds, here's Jump's scooter feed for LA: https://gbfs.uber.com/v1/laxs/free_bike_status.json

**Comment by barbeau** [comment]
Looks like this same pattern works for other cities - here's Tampa's Jump scooter feed:
https://gbfs.uber.com/v1/tpas/gbfs.json

**Comment by d-wasserman** [comment]
I am seeing this pattern as well across all of Jumps systems. All of them are 404.  Exception might be Chicago/DC. Chicago now seems to not have a working free_bike_status.json, but DC does.

**Comment by d-wasserman** [comment]
Is it possible to add an active or deactivated column to the systems.csv? I think for situations where an operator is intentionally keeping a url up but intentionally not providing data there should be some flag indicating they are not providing data. Or would the solution be to remove them from the CSV altogether?

**Comment by jcn** [comment]
The Jump feeds were updated in #190. As for an activated/deactivated column in systems.csv, I worry that we would end up with a lot of cruft over time. There's also a larger question about moving systems.csv to its own repo, so for the time being, I'm proposing that invalid feeds are removed from the file to keep it as clean as possible.

**Comment by d-wasserman** [comment]
This makes sense to me. I just was not sure how this would be managed. I can see concerns in either case. Thanks for the update.
