### ISSUE TITLE
Lime LA has NULL bike_id values

### ISSUE THREAD

**Issue by Oobhuntoo** [MobilityData/gbfs#179]
https://data.lime.bike/api/partners/v1/gbfs/los_angeles/free_bike_status

I noticed that the bike_id values in the above link for Lime free bike status data are all null. Is this because Lime stopped reporting their bike_id's for security reasons?

**Comment by Empty2k12** [comment]
I would love some insight from Lime on this. Which security problems am I not seeing by having this data openly accessible for everyone to use? 
If I understand it correctly, the Scooter ID cannot be linked to a specific rider but only allows a scooter location to be tracked around the city. Was this the reason why this data was removed?
Maybe @johnpena can help answer as he seems to be working for Lime.

**Comment by mplsmitch** [comment]
@Empty2k12 - you're a little late to the party on this,  see here for how IDs are linked to individuals:  https://github.com/NABSA/gbfs/issues/146

hence the need for auth on feeds containing IDs

**Comment by Empty2k12** [comment]
@mplsmitch Thanks for making me aware of #146 there are some interesting points mentioned there, and I can see why Scooters might be a problem. #146 was closed in favor of #147 where I also left a comment.
Our use case is fixed stations where one can trace rides only from station to station, which does not leak any PII.
I think removing `bike_id` altogether is jumping to conclusions too quickly. Shouldn't the judgment lie with the operators themselves if data could be traced back to a specific user? Maybe the standard should point out these improbable possibilities of re-id and instead encourage operators to decide if their data can be used in such ways? Maybe there are also other mitigations that might be employed to prevent re-id. 
In the end, it really depends on the location and type of vehicle used.
