### ISSUE TITLE
Request for information: Bikeshare operating rules (Docked and Dockless)

### ISSUE THREAD

**Issue by christrillium** [MobilityData/gbfs#186]
@MobilityData is hoping to get some input on the following question.

There are many different possible rules for docking:
    - docking at a dock
    - locking to any pole or rack
    - parking at a virtual station
    - completely dockless (e.g. scooters)
    - some can be both dockless and docked (e.g. free floating e-bikes that can be charged at a 
       dock).

Are there any known cases where a system has certain vehicles that can only be docked, while others can free float?

**Comment by hunterowens** [comment]
@christrillium Metro Bikeshare in LA meets that requirement, in the sense that there are two systems 

[System Map](https://bikeshare.metro.net/stations/) 

DTLA + area, San Pedro: Docked Regular and EBikes 

Noho, Palms / Culver City / Venice Areas: Smart Bikes, where the are smart bikes / dumb docks, lock to dock for free / lock to bike rack / anywhere for small fee. 

A smart bike _cannot_ be put into a regular dock, nor can an ebike / regular bike be docked at a smart bike "dock"

**Comment by mplsmitch** [comment]
Currently Minneapolis has both a docked and dockless fleet. Dockable bikes
must be returned to stations, dockless bikes have to be parked in
designated virtual stations. The exception is on the University campus
where all public bike racks have been designated as virtual stations. In
some cases there are virtual station adjacent to physical stations but not
every where.


Lyft's 2020 plans for Minneapolis include ebikes that can be docked at a
station along with regular bikes, but they can also be locked at a
designated rack, what they're calling a lite station. These will take the
place of the current virtual stations and dockless bikes.

**Comment by christrillium** [comment]
@hunterowens @mplsmitch Thank you both, these are helpful use cases.

**Comment by heidiguenin** [comment]
Closing now with the geofencing proposal passed.
