### ISSUE TITLE
Request for Input: GBFS Best Practices

### ISSUE THREAD

**Issue by christrillium** [MobilityData/gbfs#193]
Hello All,

Mobility Data is developing a set of best practice standards similar to https://gtfs.org/best-practices/ and we need your input. Please take a look at our [GBFS Best Practices [working doc]](https://docs.google.com/document/d/1ffAUlMjgsIOVLfDdONGjpruJh4NtMzVqrygxs3JrS8I/edit#) and provide feedback.

**Comment by Empty2k12** [comment]
I left some comments on the doc. I think the foundation is excellent, although there's some discussion happening around #147 and location accuracy there left to discuss further!

**Comment by mplsmitch** [comment]
Work on Best Practices is continuing based on the feedback we have received. Input has been compiled into a new [GBFS Best Practices v2 [working doc]](https://docs.google.com/document/d/1-G23eh6IhF1yIUKeVo4pUsMBxBkeeSl2jWY2AiZEUvs/edit?usp=sharing). This document will be used to create breaking and non-breaking PRs to incorporate these changes into the spec. Please take a look and provide feedback
