### ISSUE TITLE
Next additions to vehicle type definitions

### ISSUE THREAD

**Issue by heidiguenin** [MobilityData/gbfs#199]
With voting open on #136 - the "minimum viable proposal" for defining vehicle types & jumpstarting GBFS' ability to represent what operators are putting into service - I'd like to start a discussion about the next high priority additions to consider going forward. It was a time consuming effort to get to the proposal that's on the table, and I want to make sure everyone has a place to collect the ideas that didn't make it to MVP but are still needed for future enhancements.

Some factors that come to mind include whether the vehicle is a cargo vehicle, how many passengers it can take, whether the rider(s) are covered, how many wheels the vehicle has. 

@mplsmitch listed some specific examples [here](https://github.com/NABSA/gbfs/pull/136/files#r328685825), too, including adaptive bike examples.

**Comment by evansiroky** [comment]
I think it would be useful to have links to images of the vehicles. A picture says 1,000 words.

**Comment by heidiguenin** [comment]
Unsurprisingly, many of the same issues that have been raised by GBFS stakeholders with respect to vehicle types are also being raised on the MDS side - see ["Extend vehicle type definitions to improve ability to report on equity, access, and safety." ](https://github.com/openmobilityfoundation/mobility-data-specification/issues/426)

On the GBFS end, we'll need to balance providing increasingly detailed vehicle information with the potential privacy implications of that information. i.e. as vehicles are described in greater and greater detail (# of wheels, sitting/standing, cargo space, type of power) and diverse vehicle types are available throughout a service area, it may become easier to determine which vehicle has moved from point A to point B using a public GBFS dataset. 

So I'd love also to hear from folks about their considerations on that topic!
