### ISSUE TITLE
Migrate Google Doc to markdown pages

### ISSUE THREAD

**Issue by fkh** [MobilityData/gbfs#2]
The spec file should be called `gbfs.md` and should conform to this style guide: https://github.com/NABSA/gbfs/wiki/Style-Guide

The source document is here: https://docs.google.com/document/d/1BQPZCKpem4-n6lUQDD4Mi8E5hNZ0-lhY62IVtWuyhec/edit#

Note: there are some outstanding comments in the Google Docs which should be discussed with @jcn during migration if they're not resolved yet.

**Comment by rompic** [comment]
fyi: I've just added a few comments to the google docs document

**Comment by jcn** [comment]
@rompic Now that this has been merged in to master, please feel free to open new issues here on Github for public discussion vs in the Google doc. Thanks.

**Comment by rompic** [comment]
Perfect. Thx
