### ISSUE TITLE
Please tag the repository! :)

### ISSUE THREAD

**Issue by tmontes** [MobilityData/gbfs#200]
Hello all,

Thanks for the contributions in PR #188 that has been merged about a week ago.
Could we please have the repository tagged? I'd expect, at least, a `v1.0` tag that pinpoints which of the more than 20 commits claiming to be version 1.0 in their version history sections is actually version 1.0.

Again thanks.

**Comment by barbeau** [comment]
I just pushed a tag for `v1.0` that points to https://github.com/NABSA/gbfs/commit/df473ca4adbff982d67b50ac00b625191591d8f8:
https://github.com/NABSA/gbfs/tree/v1.0

@jcn @antrim @heidiguenin Does this look right to you?  If so, we should create [a GitHub release](https://github.com/NABSA/gbfs/releases) from this tag with an explanation of what it contains. I scanned the commits and pull requests in the repo going back a bit and it seems like everything prior to PR #188 for versioning were clarifications that could still be called part of v1.0.

**Comment by barbeau** [comment]
@tmontes I talked to @antrim and @heidiguenin offline and they confirmed that this tag looks good, so I went ahead and created a v1.0 release as well:
https://github.com/NABSA/gbfs/releases/tag/v1.0

**Comment by tmontes** [comment]
@barbeau, thanks. I got the tag on my side. :)
