### ISSUE TITLE
Add creative commons license for GBFS

### ISSUE THREAD

**Issue by fruminator** [MobilityData/gbfs#22]
Per a colleague from Portland Trimet, who (a) was involved in first development and use of GTFS, and (b) is involved with OpenTripPlanner which is likely to be a consumer of GBFS:

Needs a license for public use.  GTFS uses Creative Commons license. See bottom of page:
https://developers.google.com/transit/gtfs/reference

Specifically: "Except as otherwise noted, the content of this page is licensed under the Creative Commons Attribution 3.0 License, and code samples are licensed under the Apache 2.0 License. For details, see our Site Policies."

@mplsmitch any reason you wouldn't want to just add this?

**Comment by mplsmitch** [comment]
I have no issues with that

_Mitch Vars_

**Comment by fruminator** [comment]
@dfried it would be great if we could add this license statement to the main gbfs.md file.  @jcn and @alleyhector have edited this file in the past.

**Comment by jcn** [comment]
As per the standard method of doing this, I have submitted a PR for this change (with some modifications to the original language @fruminator suggested).
