### ISSUE TITLE
Station information not reported for stations temporarily unavailable 

### ISSUE THREAD

**Issue by Noe-Santana** [MobilityData/gbfs#223]
Hello everyone.

In daily operations it is common to find a station that is temporarily unavailable, due to some reasons such as a malfunction, innacesibility, maintenance, reconfiguration, etc.

I found that in some systems, when a station is installed but does not rent or receive bikes according to the "station_status", the information about the station does not appear in the "station_information", therefore, it is not possible to do a geo-referenced monitoring of the stations that are installed but not available

Should some rules be established about the relationship between these two tables? I think this is something important because it may be related to the service level of the stations; If a station is temporarily down, it must be informed, not just hidden in our applications.

P.D.
In some cases, even when the "station_status" says that a station is installed, renting and receiving bicycles, it does not appear in the "station_information".

**Comment by heidiguenin** [comment]
@Noe-Santana We're going to be getting back to work on the GBFS best practices #193  - including determining what requests like this belong in the spec itself v best practices. We can make sure this gets discussed there, too.

**Comment by mplsmitch** [comment]
@Noe-Santana We've taken this issue up in Best Practices #193. Stations displayed in the `station_information` feed will be required to appear in the `station_status` feed and vice-versa. There's also additional guidance on handling stations that are temporarily down. There's a new [Best Practices document ](https://docs.google.com/document/d/1-G23eh6IhF1yIUKeVo4pUsMBxBkeeSl2jWY2AiZEUvs/edit?usp=sharing)that will be used to incorporate these changes into the spec, please check it out and give feed back.
