### ISSUE TITLE
Fields with missing types in system_information.json

### ISSUE THREAD

**Issue by evansiroky** [MobilityData/gbfs#226]
Are the fields `attribution_organization_name` and `attribution_url` supposed to be string and URL respectively?

<img width="1307" alt="Screen Shot 2020-03-06 at 11 21 39 AM" src="https://user-images.githubusercontent.com/3112493/76115309-cdc50700-5f9c-11ea-8e05-1bd872ffaf2f.png">

**Comment by antrim** [comment]
Yes. Good catch.

**Comment by barbeau** [comment]
Thanks @evansiroky! This is fixed in https://github.com/NABSA/gbfs/commit/d4b49e0a50def02aa32e9cd9f1221fef4b05c34f.
