### ISSUE TITLE
When to consider data from a feed outdated?

### ISSUE THREAD

**Issue by bddq** [MobilityData/gbfs#232]
Hi,

Is file data considered as outdated when `last_updated + ttl < current_timestamp` ?
Maybe `last_updated` field will never change if data in that feed is not updated (i.e. system closure) and so `last_updated + ttl < current_timestamp` will be always true until data changes...

Thanks for your help/ideas...
Benoit

**Comment by mplsmitch** [comment]
Some additional guidance has been added in #271 - Short version: realtime files like `station_status` and `free_bike status` should be < 5mins. For others like `regions` or `calendar` that would rarely change the `ttl` might be much longer
