### ISSUE TITLE
COVID-19 Response

### ISSUE THREAD

**Issue by josee-sabourin** [MobilityData/gbfs#244]
In light of COVID-19, many shared mobility providers are making modifications to their service, be it providing reduced rates for frontline heroes, installing hand sanitizer at docking stations, or more frequent cleaning. We're interested in understanding how you are communicating your COVID response with your users, and if you're using GBFS to do so. If you aren't using GBFS, why not, and what are you doing instead? 

Essentially the question is: Is the specification sufficient in disseminating your COVID-related messages to users or should modifications be made? 

We would love to hear from both producers and consumers on this. Thanks!

**Comment by mplsmitch** [comment]
I had the same question a while a go and looked at `system_alerts.json` for a  number of producers. The only system I was able to find with a COVID-19 message was Bixi:

[https://api-core.bixi.com/gbfs/fr/system_alerts.json](https://api-core.bixi.com/gbfs/fr/system_alerts.json)
