### ISSUE TITLE
Adaptive Bikeshare

### ISSUE THREAD

**Issue by josee-sabourin** [MobilityData/gbfs#248]
We've been seeing a handful of cities piloting or deploying adaptive bikeshare programs in the past few years. MobilityData has compiled a [small research document](https://docs.google.com/document/d/198ACZ3bmsDqPydWtY6TiZAqsAuCHizPjcgArhWpzZos/edit?usp=sharing) with some of the systems and vehicles types that exist (please let us know if we've missed any!). How would you want to see this reflected in GBFS?

**Comment by heidiguenin** [comment]
With #370 open, #329 passed and merged, and the privacy thresholds for smaller fleets under discussion in #346, I'm going to close this and ask that future comments move to those issues.
