### ISSUE TITLE
Multiple auto-discovery feeds in website header

### ISSUE THREAD

**Issue by petoc** [MobilityData/gbfs#256]
It is not mentioned in docs, but I believe it should be valid to include multiple auto-discovery feeds in `head` section of website. Similar to allowed multiple RSS feeds. For example, when operator have multiple separate feeds for different cities but only single website.
```html
...
<link rel="gbfs" type="application/json" href="https://www.example.com/data/system_aa/gbfs.json" />
<link rel="gbfs" type="application/json" href="https://www.example.com/data/system_bb/gbfs.json" />
<link rel="gbfs" type="application/json" href="https://www.example.com/data/system_cc/gbfs.json" />
...
```

Probably most producers prefer to include one aggregated feed in such case, or no link at all.

**Comment by petoc** [comment]
It probably did not sound like a question, but if possible, I would like to hear some opinions from someone with experience.

**Comment by mplsmitch** [comment]
@petoc agree this is appropriate - I've added it to the documentation in the Best Practices pr  #271
