### ISSUE TITLE
Question: Encourage CORS settings for easier use?

### ISSUE THREAD

**Issue by trevorgerhardt** [MobilityData/gbfs#26]
Last week I threw together this: https://github.com/trevorgerhardt/gbfs-map to explore the participating GBFS networks. Initially, I wanted to just pull in the data on page load in the front end, first querying the `systems.csv` file in this repo and then pulling in the `gbfs.json` file for a system when it was needed. A problem that quickly arose is that certain CORS settings disallow direct requests from a browser. To see an example I queried the Cabi `gbfs.json` from the Chrome console and it worked, but the Monash system failed.

<img width="813" alt="screenshot 2016-05-11 08 39 33" src="https://cloud.githubusercontent.com/assets/776780/15182834/0f7244aa-1754-11e6-8ead-68d3c88e5003.png">

If each system added to their OPTIONS header: `Access-Control-Allow-Origin: *`, we wouldn't need to proxy through an additional system.

Learn more about CORS here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by cubbi** [comment]
Hey @trevorgerhardt,

Please check again and let me know if it works for you. Thanks!

**Comment by trevorgerhardt** [comment]
@cubbi awesome! Do you have the ability to update all of the systems? Didn't realize there was central control.

**Comment by cubbi** [comment]
@trevorgerhardt we deployed that change across all SocialBicycles systems - you mentioned monash, and it's running on our equipment, so we have been able to fix that.

**Comment by trevorgerhardt** [comment]
Nice. So the only that fails now is BCycle's Heartland: `https://gbfs.bcycle.com/bcycle_heartland/gbfs.json`

**Comment by jcn** [comment]
Anyone from BCycle around who can make this change?

cc @jasongdove @mplsmitch

**Comment by jasongdove** [comment]
All BCycle systems have been updated.

**Comment by jcn** [comment]
:+1:
