### ISSUE TITLE
Enhance free_bike_status.json schema to add provider_name .

### ISSUE THREAD

**Issue by ebebpl** [MobilityData/gbfs#273]
Hello, It will be helpful to have the provider_name (the bike operator) as part of the free_bike_status.json schema. Similar to MDS status_changes, trips schema which includes provider_name. This will help to combine multiple operator feeds into a single dashboard or analytics easily as some tools are unable to derive provider_names just based on the feed url when we combine the json data of all providers. Thanks!

**Comment by mplsmitch** [comment]
This is covered by the `operator` field in `system_information.json`

**Comment by ebebpl** [comment]
Although the operator field in system_information.json has the operator name, in a typical scenario where we ingest say 10 different operators using api GET request to free_bike_status.json it will be convenient to keep the operator name also so that additional api calls to system_information.json are not needed to figure out the operator for each incoming record.
