### ISSUE TITLE
Station type as part of station information

### ISSUE THREAD

**Issue by gerazenobi** [MobilityData/gbfs#280]
Hi there,

I would like to know whether there is a way to know if a station is of a certain type ? E.g. I would like to be able to differentiate those stations that support charging electric bikes from those that don't. 

Examples seen out there
```json
             {
                "station_id": "7656",
                "physical_configuration": "REGULAR",
                
            },
            {
                "station_id": "7657"
                "physical_configuration": "ELECTRICBIKESTATION"
                
            }
```
```json
            {
                "station_id": "1",
                "is_charging_station": true,
            },
            {
                "station_id": "7",
                "is_charging_station": false,
            }
```

Is this already supported and I don't seem to make the connection between the different files/datasets? E.g we know which types of vehicles and how many can park on the station but it will be wrong to assume that by allowing electric bikes to park that they will be able to charge as well.

Thanks in advance.

**Comment by l4b4r4b4b4** [comment]
I can only second that request! It is an essential feature, if not yet implemented.

**Comment by mplsmitch** [comment]
@gerazenobi To answer your question, this is not currently supported by the specification.  I agree that there is need for it. To start with I'd like to gather more information to better understand the needs.  Could you post the URLs for the examples you've seen?

**Comment by gerazenobi** [comment]
Thanks for the quick response.

The examples belonged to the same system but presented in 2 different ways depending on the file/dataset:
- https://toronto-us.publicbikesystem.net/ube/gbfs/v1/en/station_information
- https://toronto-us.publicbikesystem.net/ube/gbfs/v1/en/station_status

other systems sharing the same mechanism/approach:
- https://barcelona-sp.publicbikesystem.net/ube/gbfs/v1/en/station_information
- https://barcelona-sp.publicbikesystem.net/ube/gbfs/v1/en/station_status
- https://riodejaneiro-br.publicbikesystem.net/ube/gbfs/v1/en/station_information
- https://riodejaneiro-br.publicbikesystem.net/ube/gbfs/v1/en/station_status

**Comment by gerazenobi** [comment]
< reviving this issue so it doesn't go stale >

**Comment by mplsmitch** [comment]
@gerazenobi We're planning to work on this issue next month - May. If anyone has other ideas about enhancements to stations please let me know.

**Comment by mplsmitch** [comment]
I've opened a new issue on station services #326 that includes charging stations. I'd like to move this discussion over there and close this issue.  We've got this on our [road map](https://github.com/NABSA/gbfs/wiki/Roadmap) for a PR in Q3. Please provide any feedback in #326
