### ISSUE TITLE
Implementation of v2.1RC2

### ISSUE THREAD

**Issue by mplsmitch** [MobilityData/gbfs#282]
We'd like to make v2.1 official as soon as possible. Under the terms of the governance, before that can happen we need a producer and a consumer to implement it. Is anyone publishing, or aware of a producer who is publishing v2.1? If so, please post a link to the feed.

CC: @sfaubert1  @davidlewis-ito

**Comment by sfaubert1** [comment]
Hi! We have a partial implementation of GBFS 2.1-RC2. For example:
https://toronto.publicbikesystem.net/customer/gbfs/v2/

It's missing `system_information.json` and maybe `free_bike_status.json` (also we need to adjust `max_range_meters` in `vehicle_types` feed) as per requirements of https://github.com/NABSA/gbfs/blob/v2.1-RC2/gbfs.md

Full 2.1-RC2 implementation should be completed soon, we'll keep you posted.
