### ISSUE TITLE
Missing a couple of french bike-share services

### ISSUE THREAD

**Issue by UltrashRicco** [MobilityData/gbfs#291]
### **Have you read our [FAQ](https://gbfs.mobilitydata.org/support)? It’s possible your question can be answered there!**
Yes

### **What is the issue and _why_ is it an issue?**
Three bike-share services in France, namely Optymo in Belfort, VCub in Bordeaux, V'lille in Lille, are missing from this page. The GBFS feeds are listed on this page: https://transport.data.gouv.fr/datasets?q=gbfs

### **Please describe some potential solutions you have considered (even if they aren’t related to GBFS).**
Use feed links from this page: https://transport.data.gouv.fr/datasets?q=gbfs
Optymo, Belfort, France, system provider is Smoove: https://belfort-gbfs.klervi.net/gbfs/gbfs.json
VCub, Bordeaux, France, system provider is Keolys: https://transport.data.gouv.fr/gbfs/vcub/gbfs.json
V'lille, Lille, France, system provider is Keolys: https://transport.data.gouv.fr/gbfs/vlille/gbfs.json

Also, not listed on the aforementionned page is the new service in Carcassonne:
CycloLib, Carcassonne, France, system provider is Smoove (backend by Urban Sharing): https://gbfs.urbansharing.com/cyclolib.fr/gbfs.json

### **Is your potential solution a breaking change?**
- [ ] Yes 
- [x] No
- [ ] Unsure

**Comment by mplsmitch** [comment]
These feeds have been added - thanks!

**Comment by UltrashRicco** [comment]
Great, I hope it helps, thanks!
