### ISSUE TITLE
irregularities in geofencing_zones.json

### ISSUE THREAD

**Issue by viestat** [MobilityData/gbfs#308]
### whoami
My name is Andrés Viesca and I am a software engineer at [Dott](https://ridedott.com/), I have been working on implementing and maintaining Dott's GBFS service ([gbfs.api.ridedott.com](gbfs.api.ridedott.com)).

### **What is the issue and _why_ is it an issue?**

The current specification for `geofencing_zones.json` has some irregularities, which are an issue to me since they make the specification confusing: 
1. The fields described in [geofencing_zones] do not match its own [example][geofencing_zones-example].
   a. Field `geofencing_zones` is indicated to be of type `GeoJSON FeatureCollection`, however in the example this is an array:  
   ```json
   {
     "geofencing_zones": [{...}]
   }
   ```
   b. The `rules` field is indicated to be of type `Array`, however in the example this is an `object`:
   ```json
   {
     "geofencing_zones": [
       {
         "type":"FeatureCollection",
         "features": [
           {
             "type":"Feature",
             "geometry": {...},
             "properties" : {
               ...,
               "rules": {...}
             }
           }
         ]
       }
     ]
   }
   ```
2. The  `rules` field is indicated to be optional, however it holds two required fields: `ride_allowed` and `ride_through_allowed`. Are these only required if there is a rule present?  

3. The [geofencing_zones' example][geofencing_zones-example] does not include de common fields for all json files as indicated in the  [JSON Files Output Format](https://github.com/NABSA/gbfs/blob/master/gbfs.md#output-format), which are present in every other example.

### **Please describe some potential solutions you have considered (even if they aren’t related to GBFS).**
The solution would be:
For points **1.a** and **1.b**, Clarification is needed, once that is in place,  updating either the [example][geofencing_zones-example] or the table description to accurately reflect what is expected for the [geofencing_zones.json] endpoint will be needed. 
For point **2**, adding the necessary clarification (maybe in the filed description).

For point **3**, adding the common JSON fields to the [example][geofencing_zones-example].

### **Is your potential solution a breaking change?**
- [ ] Yes 
- [x] No
- [ ] Unsure

The changes needed are only to make the specification consistent and clear for any consumer, it does not add, edit or remove fields or endopoints, therefore it is not a breaking change.

[geofencing_zones]: https://github.com/NABSA/gbfs/blob/master/gbfs.md#geofencing_zonesjson-added-in-v21
[geofencing_zones-example]: https://github.com/NABSA/gbfs/blob/master/gbfs.md#example-11

**Comment by mplsmitch** [comment]
Hello @viestat,
Thank you for bringing these to our attention.  I have incorporated your suggestions into v3.0-RC and v2.2. 
To recap:
- `geofencing_zones` is of type `GeoJSON FeatureCollection` .  It's no longer an array in the example JSON
- the `rules` field is an array, it's no longer an object in the example JSON
- `ride_allowed` and `ride_through_allowed` are Conditionally REQUIRED when `rules` is defined
- The standard file common fields `last_updated`, `ttl` and `version` have been added to the example JSON

**Comment by mplsmitch** [comment]
Closing this - corrections are in #311

**Comment by viestat** [comment]
@mplsmitch Thank you for your edits!

**Comment by janegao2019** [comment]
Hi there, can you please help unsubscribe me? Thanks!
