### ISSUE TITLE
Extending vehicle_types.json

### ISSUE THREAD

**Issue by josee-sabourin** [MobilityData/gbfs#319]
### **What is the issue and _why_ is it an issue?**

In version 2.1 of GBFS, vehicle types were added to the specification to account for the increasing variety of vehicles available for on-demand hire. These vehicle types were added as part of a Minimum Viable Proposal (MVP). Since then, we have seen an increase in the need for providing more granular vehicle details to better equip travellers with the information they need for their trips. For the purpose of this needs assessment, vehicle details specific to carsharing have been omitted to avoid overlapping on [work that is already being done](https://docs.google.com/document/d/1bgNsiTcTfjKxG6khGq0ro0x-vEaToihp0_t-krGyj1o/edit?ts=606c5d87) on the subject.

### **Please describe some potential solutions you have considered (even if they aren’t related to GBFS).**

MobilityData has drafted a [needs assessment](http://bit.ly/vehicle-types-needs) surveying the bike, scooter, and moped industry to determine what vehicle attributes, accessories, and specifications are widely included, and promoted on provider or manufacturer websites. This issue is a means of starting a discussion on which of these features (or others we've missed!) would be beneficial to include in the next iteration of `vehicle_types.json`, and how they could be modelled. Please feel free to discuss in this thread or to comment directly in the document. 

Note: The way features are outlined in this needs assessment does not necessarily mean this is how they will be represented in the specification. For example: wheel size and seat height may be grouped into a `rider_height` field that would display the height range of riders the vehicle can accommodate. 

### **Is your potential solution a breaking change?**
- [ ] Yes 
- [x] No
- [ ] Unsure

EDIT: The extension proposal is now available [here](https://docs.google.com/document/d/1P_oDBnFvr9qzo0_5YbnrCDYptFQV9ZUOJGfi8ACD1GE/edit#).

**Comment by schnuerle** [comment]
Thank you for doing work on this important issue. At the [OMF](https://github.com/openmobilityfoundation) are also working on expanding the detail in vehicle types for our upcoming [MDS 1.2.0](https://github.com/openmobilityfoundation/governance/wiki/Release-1.2.0) release. We are currently aligned with your MVP, but have many use cases for not just vehicle types but vehicle properties (eg for various physical accessibility needs). There are about 3 issues that could be impacted by vehicle types ([self driving vehicles and delivery robots](https://github.com/openmobilityfoundation/mobility-data-specification/issues/521), [vehicle modes and properties](https://github.com/openmobilityfoundation/mobility-data-specification/issues/614), and maybe [mobility types](https://github.com/openmobilityfoundation/mobility-data-specification/issues/574)). Looking at these, we may need a new explicit issue to talk about types/properties in more detail. 

We'd like to continue aligning with on vehicle classifications to make things easier on everyone, so we will stay engaged and help how we can.

**Comment by josee-sabourin** [comment]
Hi all! 

After some discussions and feedback from community members, MobilityData has drafted an [extension proposal](https://docs.google.com/document/d/1P_oDBnFvr9qzo0_5YbnrCDYptFQV9ZUOJGfi8ACD1GE/edit#) including what appear to be the most requested vehicle type enhancements. We are going to hold off on making this a pull request until we receive more feedback on the features that have been, or should have been, included in the proposal. As always, comments are welcomed either in this thread or on the doc itself.

**Comment by hbruch** [comment]
Thanks for your effort, @josee-sabourin and MobilityData, I'm looking forward to seeing this in the standard, especially the cargo_bicycle addition.

I'd love to see the addition of a photo_url property:
- photo_url: (Optional, URL) URL to an image/photo showing a vehicle of this type. Aspect ratio should be 16x9, recommended resolution 1280 x 720 or 1920 x 1080 pixels, recommended format jpeg.

**Comment by sven4all** [comment]
Hi,

I think this is a good proposal. What are the steps to move forward to get it officially adopted in MDS and GBFS? We in the Netherlands would like to start using it and it would be nice to to it directly in an international standardized way. 

Best regards,

Sven

**Comment by josee-sabourin** [comment]
A PR has been opened for this issue over at #370! 

@hbruch - the question of image is being discussed on the carsharing proposal over at #347, however in a recent vote, vehicle_type icons have now been added to the specification, you can find the conversation over at #330. 

Now that the PR is open, we will close this thread and move the discussion to #370.
