### ISSUE TITLE
Station Services Needs Assessment

### ISSUE THREAD

**Issue by mplsmitch** [MobilityData/gbfs#326]
### **What is the issue and _why_ is it an issue?**
As station hardware and services evolve, there is a need to represent a wider array of services and attributes at the station level.  The presence of non-standard fields in feeds describing station services and hardware indicates a need for extension to the specification.  

### **Please describe some potential solutions you have considered (even if they aren’t related to GBFS).**

MobilityData has drafted a [needs assessment ](https://docs.google.com/document/d/1cd7pLD9bmGZSQYsseMez5JM3J9xznzEUETvPnUvNnYQ/edit?usp=sharing)including a number of potential use cases that could be addressed in a future extension to the specification. 

Potential additions to the specification might include:

- Fields that would allow operators to describe services available at the station along with hours and dates of availability.
- Fields that would better describe station hardware and related services like vehicle charging or the presence of a payment kiosk.
- Fields that would describe features of the station environment like lighting or accessibility issues.

Please [comment on the needs assessment document](https://docs.google.com/document/d/1cd7pLD9bmGZSQYsseMez5JM3J9xznzEUETvPnUvNnYQ/edit?usp=sharing) or here in this issue. We are particularly interested hearing from data producers and consumers who have an interest in the use cases identified in the needs assessment. We're also interested in identifying additional needs related to station services and hardware.

### **Is your potential solution a breaking change?**
- [ ] Yes 
- [ ] No
- [x] Unsure

**Comment by heidiguenin** [comment]
This issue has been moved to PR #340  - I'm closing this issue. Please continue the conversation on the PR.
