### ISSUE TITLE
The GitHub issue template contains a dead link

### ISSUE THREAD

**Issue by thbar** [MobilityData/gbfs#334]
Hello! My team at https://transport.data.gouv.fr and I are going to open an issue. I looked at the "issue template" (https://github.com/NABSA/gbfs/blob/master/.github/ISSUE_TEMPLATE/new-issue-template.md) and noticed that the FAQ points to a dead link (https://gbfs.mobilitydata.org/support).

I am not sure what the correct new link is, but happy to propose a PR once I have that information!

**Comment by mplsmitch** [comment]
Thanks @thbar - I've fixed the link
