### ISSUE TITLE
Proposal for overlapping geofencing zones

### ISSUE THREAD

**Issue by istaheev** [MobilityData/gbfs#348]
### Who am I

I am working at [Voi](https://www.voiscooters.com), my name is Ilya.

### **What is the issue and _why_ is it an issue?**

Current GBFS version doesn't say anything about overlapping zones and what to do if such happens. However overlapping zones is an useful concept to solve some common problems, for example to introduce a smaller restrictions zone over a bigger "ride allowed" one, etc. 

Since some zones can overlap their rules and properties can overlap as well creating conflicts, for example when one zone allows to park while the other one disallows it. The specification should specify a way to resolve such conflicts.

### **Please describe some potential solutions you have considered (even if they aren’t related to GBFS).**

One way to solve this is to introduce priorities for zones as an unsigned integer. If a location belongs to multiple zones then rules from a zones with higher priority will have advantage over rules from zones with lower priorities.

The proposed `priority` field could be made optional, in this case it should have default value of 0. This will keep the implementation compatible with the current version.

### **Is your potential solution a breaking change?**
- [ ] Yes 
- [X] No
- [ ] Unsure

**Comment by josee-sabourin** [comment]
Hi Ilya, welcome to the repo! 

Currently the `rules` field states: 
> In the event of colliding rules within the same polygon, the earlier rule (in order of the JSON file) takes precedence.
**In the case of overlapping polygons, the combined set of rules associated with the overlapping polygons applies to the union of the polygons. In the event of colliding rules in this set, the earlier rule (in order of the JSON file) also takes precedence.**

Can you tell us the specific case where this language doesn't meet your need?

**Comment by istaheev** [comment]
Hi Josee,

> Currently the `rules` field states:
> 
> > In the event of colliding rules within the same polygon, the earlier rule (in order of the JSON file) takes precedence.
> > **In the case of overlapping polygons, the combined set of rules associated with the overlapping polygons applies to the union of the polygons. In the event of colliding rules in this set, the earlier rule (in order of the JSON file) also takes precedence.**

Shame on my head, how could I miss this? Thank you, this looks like a solution to our problem, the issue can be closed.

Probably adding a more structure to the document will help future developers locate such things easier :)
