### ISSUE TITLE
Change structure of feeds to be single key-value pairs in gbfs.json

### ISSUE THREAD

**Issue by afischer** [MobilityData/gbfs#36]
Currently, the "feeds" array contains an array of feed objects with the properties `name` and `url`. This structure seems redundant, as this feed object has no additional values. In addition, there is no explicit ordering of the feeds in `gbfs.json`.

Having the feeds list be changed to a key-value pair of the format `"<feed_name>": "<feed_url>"` would make the auto-discovery feed easier to parse and more terse. Using the [example from the spec](https://github.com/NABSA/gbfs/blob/master/gbfs.md#gbfsjson), an updated `gbfs.json` would look like this:

``` JSON
{
  "last_updated": 1434054678,
  "ttl": 0,
  "data": {
    "en": {
      "feeds": {
        "system_information": "https://www.example.com/gbfs/en/system_information",
        "station_information": "https://www.example.com/gbfs/en/station_information"
      },
    "fr" : {
      "feeds": {
        "system_information": "https://www.example.com/gbfs/fr/system_information",
        "station_information": "https://www.example.com/gbfs/fr/station_information"
      },
    }
  }
}
```

**Comment by jcn** [comment]
Are you arguing for or against explicit ordering? 

I understand wanting to use the feed name as the key, but that would necessarily remove the ability to add any additional metadata about the feeds later down the road. This doesn't seem like a good trade off at this point, especially since it would require a brand new version of gbfs at this point since the current schema is already deployed pretty broadly.

**Comment by afischer** [comment]
I would say against—there is no ordering, and different bike shares order the differently anyway.

What types of additional information do you think we may want in this feed that we wouldn't/couldn't/shouldn't put in the top-level header? And yeah, if implemented this would definitely be a "breaking" change so it would have to wait.

**Comment by fkh** [comment]
Do we have a bucket for v2 items?

**Comment by jcn** [comment]
I won't pretend to know what information we would want here, but the current schema is flexible enough to allow for it if we end up with something. Remember that gbfs has been out in the public for only about 6 months. 

I would hope that nobody is assuming that the feeds array is supposed to be in a particular order!

Happy to leave this suggestion here as a proposed breaking change but unless there's broad support I can't imagine this being implemented in the near future.

**Comment by afischer** [comment]
@fkh Looks like there is a [2.0 milestone](https://github.com/NABSA/gbfs/milestones/2.0)

@dfried — I know we spoke a lot about this yesterday, do you have anything to add?

**Comment by barbeau** [comment]
Not sure I have voting rights here :), but if I do I'm a -1 on this.  It's a breaking change and IMHO it unnecessarily restricts the spec.  As far as making the feed easier to parse, there are data binding JSON parsing libraries like Jackson that make this fairly trivial even for complex data models.  And order of elements definitely shouldn't be assumed - it can be difficult to enforce field ordering with some JSON generation libraries.
