### ISSUE TITLE
Clarifying geofencing_zones.json language about intersections

### ISSUE THREAD

**Issue by heidiguenin** [MobilityData/gbfs#361]
### **What is the issue and _why_ is it an issue?**
In the [geofencing documentation](https://github.com/NABSA/gbfs/blob/master/gbfs.md#geofencing_zonesjson-added-in-v21), `rules` states:
"In the event of colliding rules within the same polygon, the earlier rule (in order of the JSON file) takes precedence.
In the case of overlapping polygons, the combined set of rules associated with the overlapping polygons applies to the union of the polygons. In the event of colliding rules in this set, the earlier rule (in order of the JSON file) also takes precedence."

As more stakeholders begin implementing geofencing, it has become clear through discussion in the GBFS slack channel (request an invite [here](https://bit.ly/mobilitydata-slack)) that this language is confusing **and** does not conform to the intent of the rule. Specifically, the intention is that, in the case of overlapping polygons, the combined set of rules applies to the _intersection_, not to the _union_.  MobilityData would like to update the language and provide some clarifying examples, but before we do, we want to understand if **anyone** is currently implementing `geofencing_zones.json` treating overlapping polygons rules as a geographic _union_. If not, then we can clarify the language without creating a breaking change and requiring an extra governance step.

### **Is your potential solution a breaking change?**
- [ ] Yes 
- [ ] No
- [ x] Unsure

**Comment by josee-sabourin** [comment]
Hi all! We talked about this issue during the Developers' Workshop, see details [here](https://docs.google.com/document/d/1jAwKY9e7rz3Do6EkUecR59Oj5Nm5bM3isNN3plvSE3s/edit#bookmark=id.z54ws8tdgdr4).

**Comment by mplsmitch** [comment]
This is covered in PR #384
https://github.com/NABSA/gbfs/pull/384
