### ISSUE TITLE
New form_factor vehicles

### ISSUE THREAD

**Issue by sven4all** [MobilityData/gbfs#365]
In the Netherlands we would like to have a little bit more detailled form_factor in the standard.

First we would like to introduce the shared cargo bicycle in the standard, it's a bicycle but the form factor is so specific that I think it would be a good idea to add a form factor 'cargo_bicycle' https://twitter.com/svenboor/status/1360964565136265216. 

Another form_factor we would like to distinguish is the difference between a 'snorfiets' (moped with a maximum allowed speed of 25 kph) and 'bromfiets' (moped with a maximum allowed speed of 45 kph that requires wearing a helmet). What is a proper way to do that within GBFS, because I can understand that the difference between this two kinds of mopeds is very specific for the Netherlands. 

I would like to hear your opinion before creating a proposal. 

- [ ] Yes 
- [x] No
- [ ] Unsure

**Comment by josee-sabourin** [comment]
Hi @sven4all, have you taken a look at #319? 

The proposal includes the addition of cargo bicycles and may answer your needs for the distinction between snorfiets and bromfiets. A potential solution could be both are listed as `moped`, however we add a `max_speed` field indicating the maximum speed the vehicle can attain as well as `max_permitted_speed` as proposed in #319, which is the maximum speed the vehicle is permitted to attain based on local regulations. 

What do you think?

**Comment by sven4all** [comment]
Hi Josee,

I didn't, thanks for the reference! That should work, I will have a look at #319, close this issue and continue there.
