### ISSUE TITLE
Provide JSON Schema for GBFS Documents

### ISSUE THREAD

**Issue by afischer** [MobilityData/gbfs#37]
I'm not a huge fan of [the JSON schema](http://json-schema.org/), but there are quite a few libraries [(some examples)](https://github.com/json-schema-org/JSON-Schema-Test-Suite#who-uses-the-test-suite) that use or support schema validation.

I'm currently trying to validate geoJSON, and I am shocked that there is no official schema. I think it would be helpful to developers to provide the schema ourselves.

**Comment by barbeau** [comment]
+1 for this.  It does make it easier to generate client-side code used to parse feeds, especially if you have a number of optional fields that some producers may not implement.

**Comment by thzinc** [comment]
I'd love some feedback on my PR to add schema files to the spec. :)

**Comment by antrim** [comment]
@thzinc: Could I close this issue so that we guide all discussion towards your open pull request?

**Comment by thzinc** [comment]
@antrim, that’s fine by me. (It’s not my issue, but I support it)

**Comment by antrim** [comment]
@afischer May I close this issue (to continue discussion in PR #70)?

**Comment by afischer** [comment]
Sure!
