### ISSUE TITLE
Mapping GBFS for NGSI standard. How to credit to the authors?

### ISSUE THREAD

**Issue by albertoabellagarcia** [MobilityData/gbfs#375]
I'm the responsible person for the Smart Data Models Program. This is an open program to create/document data models and to release them with an open license.  
We are mapping [GBFS](https://github.com/smart-data-models/dataModel.GBFS) to work with NGSI standard. When we create those mappings we credit the authors of the source data models. How could we identify them? (all fields are voluntary)

See an [example](https://github.com/smart-data-models/dataModel.FrictionlessData/blob/master/CONTRIBUTORS.yaml) of such credits.
A contact mail at [info@smartdatamodels.org](mailto:info@smartdatamodels.org)

**Comment by heidiguenin** [comment]
Alberto, although GBFS is, now, primarily written and maintained by the shared mobility team at MobilityData, over time there have been 80 contributors to the standard. It would probably be best to just link directly to the contributors page on the repository: https://github.com/NABSA/gbfs/graphs/contributors.

**Comment by albertoabellagarcia** [comment]
We are happy to include this link in the customization of the specification but the CONTRIBUTORS.yaml file has a precise format. All fields are voluntary. 
I know that we could extract some of this information from github API but it is also true that sometimes people change their organizations and other changes. Does GBFS have a mail list for contributors to send this possibility? This is what we did with other standards like frictionless data.

**Comment by heidiguenin** [comment]
Sorry, Alberto, there is no email list for GBFS contributors. Conversations happen here on the repo or through the GBFS slack channel on [MobilityData's workspace](https://bit.ly/mobilitydata-slack).

**Comment by albertoabellagarcia** [comment]
I got these [contributors](https://github.com/smart-data-models/dataModel.GBFS/blob/master/CONTRIBUTORS.yaml) from the Pull Requests.
I've also asked to join the mobility data workspace. 
The [mapping of the data models](https://smartdatamodels.org/index.php/gbfs-standard-mapped/) to be used with NGSI (FIWARE platform) is already published.
thanks
