### ISSUE TITLE
Define explicitly that a system/station allows station overloading

### ISSUE THREAD

**Issue by optionsome** [MobilityData/gbfs#376]
Hello,

I'm Joel and I'm working for the Digitransit project in Finland.

### **What is the issue and _why_ is it an issue?**
Currently, there is no explicit way to define vehicles can be left undocked near the stations in situations where a station is full (or even in general). This seems to be possible at least for the most bicycle rental networks in Finland. Despite the number of docks at the station not being too relevant in these situations, as it does not limit returning of vehicles, we still feel that num_docks_available information could be included in the data.

### **Please describe some potential solutions you have considered (even if they aren’t related to GBFS).**

The alternative solutions could be:
1. Add a new boolean field for stations. It could be either in station_information.json or in station_status.json depending on if it possible that a station only allows overloading sometimes or always (at least in our cases as long as stations allow renting, they also allow overloading).
2. Add a new boolean field for the system in system_information.json. At least in the systems we use, all stations allow overloading.
3. Add a new value for return_type in vehicle_types.json which defines that bicycles can be left undocked at the stations.

I think this information should be optional regardless of where it's defined.

### **Is your potential solution a breaking change?**
- [ ] Yes 
- [x] No
- [ ] Unsure

**Comment by mplsmitch** [comment]
@optionsome Can you say more about how this works in Finland? Does this mean that there are cases where bikes are left unlocked when stations are full?  

I'm familiar with City Bikes in Helsinki and I believe the bikes have a built in lock that can be used to secure the bike and end the rental when outside the station. In that case they would have a `return_type` ( `return_constraint` as of v2.3-RC2) of `hybrid` in `vehicle_types.json`.   When outside the station, the vehicle location in `free-bike_status` would be determined using the `lat` & `lon`, when docked in a station it would be `station_id` or both.

**Comment by optionsome** [comment]
I think the cases we have elsewhere in Finland are really similar to the Helsinki one. You have to return the bicycle either to one of the docks or within a certain radius of a station (the bicycle can be locked using a chain lock that is attached from both ends to the bicycle). I think these bicycles can be considered to be attached to the station more than truly free floating. I think the `hybrid` return_constraint could be used but I don't think it's necessarily as self-explaining as I would hope for someone who is looking at the data. If one was to use the free_bike_status, I think all these bicycles should have station_id defined.

**Comment by mobilitydataio** [comment]
This discussion has been closed due to inactivity. Discussions can always be reopened after they have been closed.
