### ISSUE TITLE
About Bay Wheels trip history data & metadata

### ISSUE THREAD

**Issue by HP-Nunes** [MobilityData/gbfs#388]
My main question pertains to the [Bay Wheels trip history data](https://s3.amazonaws.com/baywheels-data/index.html). There are 3 categorical values for the **rideable_type** field: _classic_bike_, _docked_bike_, and _electric_bike_. Here is the versioning timeline:

- The **rideable_type** field was introduced with the April 2020 dataset, with the following two attributes:  _docked_bike_, and _electric_bike_ (so far so good, ebikes were deployed in the Bay Area around that time, I get it).
- The _classic_bike_ attribute was introduced in the November 2020 dataset.
- All three attributes are still being used concurrently as of the latest 2021 monthly dataset.

My issue is that the difference between them is not clear to me (the attribute _classic_bike_ was introduced in the 2020 dataset alongside  _electric_bike_ and _docked_bike_; so it's not substituting for an existing variable as I had once thought). I am certain that _classic_bike_ are simply regular, non-ebikes, and I can assume by the chronology that _docked_bike_ are not ebikes either. But what's the difference? Even if it's a subtle difference per the conventions of how Lyft's charges for rides, I'd like to know!

---

### Why am I posting this here?

I'm really hoping that someone in the data team at Lyft/Bay Wheels sees this, because honestly this is starting to grind my gears.

1. I can't reach you at the email (data@baywheels.com) provided on your [Data License Agreement page](https://baywheels-assets.s3.amazonaws.com/data-license-agreement.html)!!! The email is invalid/out-of-service. And the best part? I notified @Lyft on Twitter about this in JANUARY (and before someone says "well the social media guys don't talk to the data guys": no, they clearly do, because I've pointed typos and inconsistencies in the historical dataset that were subsequently fixed through these same channels). So....what's going on here?

2. There's clearly a well-written, kept-to-date metadata sheet for GBFS feed. So what gives when it comes to the historical dataset (no, [listing the fields as bullet points](https://www.lyft.com/bikes/bay-wheels/system-data) doesn't count)? I've been working with this dataset for well-over a year, and there have clearly significant versioning changes to field's names, attributes etc. that I've had to fine comb and adjust for when wrangling the data. Why the lack of metadata for the historical dataset? 

I really don't mean to be snarky or mean-spirited, I like working with this dataset, but I also don't like beating around the bush for something that can usually be answered through standard documentation.

**Comment by mplsmitch** [comment]
@HP-Nunes Seems very unlikely that you'll get a response from Lyft here. Maybe try the email from one of their other data license agreements, e.g. 
- https://ride.citibikenyc.com/data-sharing-policy
- https://www.capitalbikeshare.com/data-license-agreement
- https://www.divvybikes.com/data-license-agreement

Also there's a citibike data Google group that might be able to help: https://groups.google.com/g/citibike-hackers

**Comment by HP-Nunes** [comment]
@mplsmitch Thanks for the suggestion! I was under the impression that the General Bikeshare Feed Specification was maintained by Lyft's staff, but upon reading the Read Me I was visibly mistaken.

**Comment by AmandaKnightKC** [comment]
I would also like to know what a docked_bike is.  Is it a bike that was taken out of circulation?  Maybe I should remove those rides.

**Comment by josee-sabourin** [comment]
Hi @AmandaBoyers! If you are looking to get clarification on the trip and history data linked above, unfortunately this is not the correct forum. Perhaps try bike-data@lyft.com, or maybe @mwillmott / @ArashMansouri can provide some further insights. 

Best of luck!
