### ISSUE TITLE
Issue with requirements of some nested objects in station_status.json and system_pricing_plans.json

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gbfs#392]
If a nested object is _required_ but the parent is either _Optional_ or _Conditionally Required_, the nested object should be described as _Conditionally Required_. 

1. In the file `station_status.json`:
- under `vehicle_docks_available`: `vehicle_type_ids` and `count` are required if `vehicle_docks_available` is defined
- under `vehicle_types_available`: `vehicle_type_id` and `count` are required if `vehicle_types_available` is defined

Those four fields are currently described as _required_. But since `vehicle_docks_available` and `vehicle_types_available` are _Conditionally Required_, the nested objects should also be described as _Conditionally Required_. 

2. In the file `system_pricing_plans.json`:
- under `per_km_pricing`: `start`, `end` and `interval` are required if `per_km_pricing` is defined
- under `per_min_pricing`: `start`, `end` and `interval` are required if `per_min_pricing` is defined

Those six fields are currently described as _required_. But since `per_km_pricing` and `per_min_pricing` are _Optional_, the nested objects should also be described as _Conditionally Required_.

**Comment by heidiguenin** [comment]
Thanks, @isabelle-dr - it does look like we represent this inconsistently right now. 

For example, in `system_information.json`:
under `rental_apps` (which is _optional_):`store_uri` is required if `rental_apps` is defined, and `store_uri` is listed as _conditionally required._

We'll make a list of these inconsistencies and get them revised.

**Comment by mplsmitch** [comment]
This has been corrected in #397 - closing issue
