### ISSUE TITLE
2021 Shared Mobility Industry Survey

### ISSUE THREAD

**Issue by josee-sabourin** [MobilityData/gbfs#402]
We have launched the MobilityData 2021 GBFS Industry Survey for all the GBFS Producers and Consumers out there!
We want to better understand the main needs and challenges you are experiencing, with respect to the specification itself, the related supportive tools and resources, and MobilityData’s management of these. 
You have until January 28th to give us feedback through the survey. 
→ https://bit.ly/2021-gbfs-industry-survey

**Comment by mplsmitch** [comment]
2021 Survey has been completed - partial summary of findings here: https://mobilitydata.org/2021-shared-mobility-industry-survey-results/
