### ISSUE TITLE
`systems.csv` Contains URLs with Characters that Should be Encoded

### ISSUE THREAD

**Issue by DaveL17** [MobilityData/gbfs#413]
### **What is the issue and _why_ is it an issue?**
Sometimes URIs within the `systems.csv` file contain URI reserved characters.  While they may not necessarily all be breaking instances, they can at times create down-stream issues with clients.  These reserved characters are listed in [RFC3986](https://www.rfc-editor.org/rfc/rfc3986).

> gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"
>
> sub-delims  = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="

To maintain best practice, these `gen-delim` and `sub-delim` characters should be Percent-encoded within any URIs.  For example, 
```
https://wrangler-mds-production.herokuapp.com/gbfs/Seattle,%20WA/gbfs.json
```
should become:
```
https://wrangler-mds-production.herokuapp.com/gbfs/Seattle%2C%20WA/gbfs.json
```
to be compliant with RFC3986.
### **Is your potential solution a breaking change?**
- [ ] Yes 
- [x] No
- [ ] Unsure

**Comment by mplsmitch** [comment]
Thanks @DaveL17 - I fixed the one you found and I don't see any others. If you come across more let us know or just open a PR.

**Comment by DaveL17** [comment]
Thanks for taking care of so quickly!

Cheers,
Dave
