### ISSUE TITLE
PBSC GBFS are not secured

### ISSUE THREAD

**Issue by bddq** [MobilityData/gbfs#419]
Hi, Benoit from VeloDispo apps on iOS.

I updated PBSC networks from last #416 / #417 PRs (@fbouchPBSC) and I found that new GBFS endpoints v2 are mentioning `http` protocol that is redirecting to `https`.
Will not be better to add `https` URLs in the `gbfs.json` file?

Regards,
Benoit

**Comment by fbouchPBSC** [comment]
Hi, you are correct!  I will raise a ticket here and have the links corrected.  Thanks

**Comment by bddq** [comment]
Any news @fbouchPBSC?

**Comment by mplsmitch** [comment]
@fbouchPBSC I noticed this continues to be an issue with the new feeds for POGOH - the URLs in gbfs.json are all http:

`{
"name": "gbfs_versions",
"url": "http://pittsburgh.publicbikesystem.net/operation/customer/gbfs/v2/gbfs_versions"
},
{
"name": "vehicles_types",
"url": "http://pittsburgh.publicbikesystem.net/operation/customer/gbfs/v2/en/vehicle_types"
},`

**Comment by fbouchPBSC** [comment]
Hi, I know.  The ticket has been raised in our system.  Awaiting a fix. 

Thanks

**Comment by fbouchPBSC** [comment]
Fix is done and will be released in the coming weeks to all PBSC systems.

**Comment by mplsmitch** [comment]
Closing Issue: This seems to be fixed in all the PBSC feeds listed in systems.csv
