### ISSUE TITLE
Breaking change in v2.3-RC2

### ISSUE THREAD

**Issue by testower** [MobilityData/gbfs#420]
As raised in slack earlier in the week.

### **What is the issue and _why_ is it an issue?**

I noticed there is a breaking change in v2.3-RC2, in vehicle_types.json, name in the conditional requirement of the new field "default_pricing_plan_id":

> “REQUIRED if both system_pricing_plans.json and vehicle_types.json are defined.”

We are unable to complete implementation of this release candidate until this is solved.

### **Please describe some potential solutions you have considered (even if they aren’t related to GBFS).**

The field should be made optional, and a conditional requirement can be added in v3.

### **Is your potential solution a breaking change?**
- [ ] Yes 
- [x] No
- [ ] Unsure

**Comment by mplsmitch** [comment]
Thanks for Flagging this @testower  - I'm updating the release candidate, should be completed sometime on Monday 3/28. I'll update this issue when the corrected release candidate is ready.

**Comment by mplsmitch** [comment]
This change has been incorporated into v2.3-RC2 along with other minor corrections
