### ISSUE TITLE
Systems should have end_date

### ISSUE THREAD

**Issue by optionsome** [MobilityData/gbfs#424]
### **What is the issue and _why_ is it an issue?**
Currently, `system_information.json` has `start_date` but no end date. If it was also possible to define `end_date`, ~~it would be possible for us to figure out from the data when the season is on for systems that don't operate throughout the year. It is common in countries with snow (such as here in Finland) that most systems only operate during summer.~~ (system_calendar solves this part). I think this information would also be useful for all systems that will permanently stop their operations.
### **Please describe some potential solutions you have considered (even if they aren’t related to GBFS).**
Adding `end_date` to `system_information.json` that would be similar to `start_date`.
### **Is your potential solution a breaking change?**
- [ ] Yes 
- [x] No
- [ ] Unsure

**Comment by optionsome** [comment]
I now realised that there is system_calendar.json which partly solves this issue. However, for permanently closing systems I think this concern is still valid.

**Comment by mplsmitch** [comment]
@optionsome 
I think you've mostly got this figured out - `systems_information.json#start_date` represents the date when the system began operations. Dates and times of service are currently handled in  `system_hours.json` and `system_calendar.json` but starting in v3.0 they will move to`system_information.json` using OSM Opening hours.

For systems that permanently stop operations, it's assumed that they would no longer be publishing feeds. This happens frequently based on the churn rate of systems listed in systems.csv. Also as a real-time data specification, historical `end_date` data like you describe would be outside the GBFS scope.

There are other sources for this type of historical data, here's an example:
https://bikeshare-research.org/#bssid:seattle

**Comment by mplsmitch** [comment]
Closing this - issue resolved
