### ISSUE TITLE
Data from Nextbike for Pittsburgh Healthy Ride doesn't work

### ISSUE THREAD

**Issue by sergip76** [MobilityData/gbfs#432]
Data from Nextbike for Pittsburgh Healthy Ride is not working:
https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_pp/gbfs.json
Does anybody know the new URL?

Thanks.

**Comment by mplsmitch** [comment]
That's no longer a nextbike system, they have a new operator and a new name. Website is pogoh.com, Here's the feed: https://pittsburgh.publicbikesystem.net/customer/gbfs/v2/gbfs.json

**Comment by sergip76** [comment]
> That's no longer a nextbike system, they have a new operator and a new name. Website is pogoh.com, Here's the feed: https://pittsburgh.publicbikesystem.net/customer/gbfs/v2/gbfs.json

Thank you very much!!

So it's necessary to change it in the systems.csv file.

**Comment by emmambd** [comment]
Hi @sergip76 - yes. Feel free to contribute a change to systems.csv. Otherwise I will make sure it's updated at the end of June.

**Comment by mplsmitch** [comment]
This has been updated in systems.csv - #433, HealthyRide is now POGOH
