### ISSUE TITLE
Add easier interface for contributions to system.csv

### ISSUE THREAD

**Issue by CourchesneA** [MobilityData/gbfs#434]
### **Have you read our [FAQ](https://gbfs.mobilitydata.org/faq)? It’s possible your question can be answered there!**
yes
### **If you are new to the specification, please introduce yourself (name and organization/link to GBFS). It’s helpful to know who we're chatting with!** 
Anthony Courchesne - [IVI](https://www.ivisolutions.ca/en/)
Attendee at IMDS / Developer workshop

### **What is the issue and _why_ is it an issue?**
In one of our discussions, we mentioned that we might get more contributions to system.csv if the contributors did not require interaction with the github repo. Currently, people need to know how to open an issue or a PR.

### **Please describe some potential solutions you have considered (even if they aren’t related to GBFS).**
One solution would be to have a google form with fields possibly corresponding to columns in the system.csv, possibly increasing the amount of contributions to the database.

### **Is your potential solution a breaking change?**
- [ ] Yes 
- [X] No
- [ ] Unsure

**Comment by josee-sabourin** [comment]
Closing this since it has been solved by #487
