### ISSUE TITLE
Is Auto-Discovery URL with access token OK?

### ISSUE THREAD

**Issue by kg-b0mbe** [MobilityData/gbfs#436]
### **Have you read our [FAQ](https://gbfs.mobilitydata.org/faq)? It’s possible your question can be answered there!**
YES
### **If you are new to the specification, please introduce yourself (name and organization/link to GBFS). It’s helpful to know who we're chatting with!** 

I'm working for shared mobility company, OpenStreet.Corp(https://www.openstreet.co.jp/) in Japan.

### **What is the issue and _why_ is it an issue?**

Is it acceptable that Auto-Discovery URL with ACCESS_TOKEN on systems.csv ? We are planning to open GBFS data on https://www.odpt.org/ then this site ask you to make your account and get your access token.After that you can access to url with your access token like this.
e.g.
https://api.odpt.org/api/v4/odpt:hellocycling/sharecycling:consumerKey=[YOUR_ACCESS_TOKEN]

Is it okay for GBFS? Does it follow the GBFS rules?

### **Please describe some potential solutions you have considered (even if they aren’t related to GBFS).**
If it is okay,  we will make pull request. It it's not okay, I will ask https://www.odpt.org/  to remove access token ati the end.

### **Is your potential solution a breaking change?**
- [ ] Yes 
- [x] No
- [ ] Unsure

**Comment by mplsmitch** [comment]
Use of access tokens is discouraged - feeds listed in systems.csv should be easily accessible to the public without requiring a token or other means of authentication. See here: https://github.com/NABSA/gbfs/blob/master/gbfs.md#accessibility

If you could persuade them to remove the token requirement that would be great. I would love to seed Japan become part of the systems catalog.

**Comment by kg-b0mbe** [comment]
Thanks for your quick answer and I'm sorry I overlooked part of accessibility. I sent email them that  use of access tokens is not encouraged and I'll see how it works.

**Comment by mplsmitch** [comment]
Resolved - closing issue
