### ISSUE TITLE
Add legal license link to the discovery feed

### ISSUE THREAD

**Issue by wrenj** [MobilityData/gbfs#45]
Can we update the discovery spec to allow a link to the legal license, something like:

Updating discovery:
https://gbfs.citibikenyc.com/gbfs/gbfs.json

To include:
{
  name: "license",
  url: "https://gbfs.citibikenyc.com/license.txt"
}

Motivation:

I work for Google and we require a legal review to import any third party data.  This would be one review per provided, and there are currently 47.  If there were a straightforward link to the license it would be easier for us to review than having to search for it on the website.

Thanks!

**Comment by mdarveau** [comment]
This sound like an easy win if it can help the adoption of the standard. We, 8D Technologies, are +1 on this.

I was wondering if we should include a way to specify that the data is simply open, but operators could use a freely available open data license (ie http://opendatacommons.org/).

**Comment by fruminator** [comment]
likewise +1 from Motivate's perspective. We've been talking with Google about importing data for our systems, and are prepared to draft and post the appropriate licenses.

**Comment by wrenj** [comment]
Here's a generic version of the standard Google Maps data license:

"We grant you a perpetual, irrevocable, non-exclusive, worldwide, royalty-free, sub-licensable license to reproduce, distribute, make derivative works based on, publicly display, publicly perform, and otherwise use the Licensed Content in connection with your products or services."

The three key factors to the license grant are:

(a) "perpetual" (meaning that the license lasts forever);

(b) "irrevocable" (meaning the Licensor can't revoke the license even if Google breaches the license terms--although the Licensor retains the right to recover monetary compensation if Google's breach damages the Licensor); and

(c) "in connection with Google products or services" (meaning we can't just distribute the Licensor's IP on a standalone basis, but instead we need to use it within Google services)

**Comment by cubbi** [comment]
+1 from Social Bicycles side as well.

**Comment by jcn** [comment]
@wrenj From Google's (and other data consumer's) perspective, is this just a convenience so you know where to look for the licenses? Will a real human will end up reading this data anyway?

My question is whether there are enough standard data licenses around that we could include an optional "type" field that would identify the license specifically: 

``` json
{ 
"name" : "license", 
"url" : "http://opendatacommons.org/licenses/odbl/1.0/",
"type" : "odbl"
}
```

While this seems nice, practically speaking it might not make any sense, so I wanted to float this out there to see whether this could/would work.

**Comment by mplsmitch** [comment]
+1 from Nice Ride

**Comment by wrenj** [comment]
@jcn - Legal approval is per license, so if multiple providers used the same, open source license we would only need to do legal approval once.  We can look at the URL to know which license is being used, so type wouldn't be necessary.  

Of the three licenses at http://opendatacommons.org/:

Public Domain Dedication and License (PDDL) — “Public Domain for data/databases”
Attribution License (ODC-By) — “Attribution for data/databases”
Open Database License (ODC-ODbL) — “Attribution Share-Alike for data/databases”

In general, we can only accept the PDDL terms. If a data provider chose to make is data available only through ODC-By or ODC-ODbL, we would not be able to use the data.

**Comment by jcn** [comment]
I've added a proposed addition to the spec to define the location of this license_url. Comments welcome.

**Comment by barbeau** [comment]
@wrenj are Google's open data license preferences you mention above posted anywhere that is easily discoverable/referenced?

I imagine it would help producers decide on a license if they knew Google's acceptable licenses.

**Comment by jcn** [comment]
As per the change made in #49 `license_url` is now part of the `system_information` feed and GBFS producers should feel free to incorporate it into their feeds. 

https://github.com/NABSA/gbfs/blob/master/gbfs.md#system_informationjson
