### ISSUE TITLE
GBFS v2.3 vehicle_type has typo

### ISSUE THREAD

**Issue by bhargav-lime** [MobilityData/gbfs#466]
### **Have you read our [FAQ](https://gbfs.mobilitydata.org/faq)? It’s possible your question can be answered there!**
Yes

### **If you are new to the specification, please introduce yourself (name and organization/link to GBFS). It’s helpful to know who we're chatting with!** 
Bhargav Jhaveri - I work with Lime

### **What is the issue and _why_ is it an issue?**
There is typo in v2.3 Spec in vehicle_types.json.
It has one of the types as scooted_seated instead of scooter_seated.
The standing counterpart is spelled correctly.

### **Please describe some potential solutions you have considered (even if they aren’t related to GBFS).**
N/A

### **Is your potential solution a breaking change?**
- [ ] Yes 
- [ ] No
- [X] Unsure

**Comment by bhargav-lime** [comment]
PR: https://github.com/MobilityData/gbfs/pull/465

**Comment by josee-sabourin** [comment]
Thanks for this, PR has been merged.
