### ISSUE TITLE
Value of lat,lon when is_reserved is true

### ISSUE THREAD

**Issue by kevinsimper** [MobilityData/gbfs#473]
Implementing the spec now for GreenMobility, but I can't see what is best practice for lat,lon when is_reserved is true?

Should it be removed? Show it be 0 in value?

https://github.com/MobilityData/gbfs/blob/master/gbfs.md#vehicle_statusjson

**Comment by kevinsimper** [comment]
I got confused with is_reserved in the context of GreenMobility car sharing. It makes sense that `is_reserved` is `true` for a docked bicycle, if customers has not yet picked up the bike.

For a dockless system, `is_reserved` would never be true, because most dockless systems see a reserved vehicle as a active reservation.

> Describes all vehicles that are not currently in active rental.

**Comment by sven4all** [comment]
is_reserved with a free floating vehicle means that the customer has reserved the vehicle but didn't start the trip yet. 

So for example, a user checks nearby bicycles or moped, reserve a bicycle or moped, walks to the bicycle or moped and starts the trip, in the in the period between reserving the bike and starting the trip the status should be is_reserved.

**Comment by mplsmitch** [comment]
Hello @kevinsimper  - we've got a proposed change to the spec in https://github.com/MobilityData/gbfs/pull/460 that needs additional votes to pass. As a GBFS producer you're eligible to vote on it. A lot of work has gone into the proposal so I'd really like to see it pass for inclusion in the next release. Please consider supporting it before voting closes at 11:59PM UTC on Friday, January 20th. Thanks!
