### ISSUE TITLE
Updated Baltimore, MD gbfs URLs

### ISSUE THREAD

**Issue by oonuttlet** [MobilityData/gbfs#476]
hi! I'm using @simonpcouch's `gbfs` package for R to map vehicle locations in Baltimore and noticed a few outdated links.

**In get_gbfs_cities() (which references `systems.csv`), a search for "Baltimore" returns 4 System IDs of `Link_Baltimore`, `lime_baltimore`, `Link_Alexandria`, and `spin baltimore` with outdated URLs**

these should be (as far as I can tell) updated to:

`bird_baltimore` = https://mds.bird.co/gbfs/v2/public/baltimore/gbfs.json
`link_baltimore` = https://mds.linkyour.city/gbfs/us_md_baltimore/gbfs.json
`spin_baltimore` = https://gbfs.spin.pm/api/gbfs/v2_3/baltimore/gbfs.json

This reflects Baltimore's non-renewal of the contract with Lime, and the new contract with Bird.

### **Is your potential solution a breaking change?**
- [ ] Yes 
- [x] No
- [ ] Unsure

**Comment by mplsmitch** [comment]
This is fixed along with some other additions in #477.  Thanks for the input @oonuttlet !

**Comment by josee-sabourin** [comment]
Closing as #477 has been merged. Thanks @mplsmitch and @oonuttlet

**Comment by mplsmitch** [comment]
Hey @oonuttlet - we've got a proposed change to the spec that needs additional votes to pass. As a GBFS consumer you're eligible to vote on it. Please consider supporting it before voting closes at 11:59PM UTC on Friday, January 20th.

https://github.com/MobilityData/gbfs/pull/460
