### ISSUE TITLE
found out one Auto-Discovery URL is invalid

### ISSUE THREAD

**Issue by kg-b0mbe** [MobilityData/gbfs#501]
### **Have you read our [FAQ](https://gbfs.mobilitydata.org/faq)? It’s possible your question can be answered there!**
Yup

### **If you are new to the specification, please introduce yourself (name and organization/link to GBFS). It’s helpful to know who we're chatting with!** 

I'm working for shared mobility company, OpenStreet.Corp(https://www.openstreet.co.jp/) in Japan.

### **What is the issue and _why_ is it an issue?**

Auto-Discovery URL below is invalid 

Roll Kelowna
https://data.rollapi.com/v1/gbfs/kelowna/gbfs.json

### **Please describe some potential solutions you have considered (even if they aren’t related to GBFS).**
Is there a procedure to report broken links to keep quality of GBFS?

I thought it would be good to have a system or rule to periodically check if the URL is valid.

### **Is your potential solution a breaking change?**
- [ ] Yes 
- [x] No
- [ ] Unsure

**Comment by mplsmitch** [comment]
This feed was removed in #506.  Roll is no longer operating in this market.

**Comment by kg-b0mbe** [comment]
Thank you for your response.
