### ISSUE TITLE
Clarification Needed: Understanding the Purpose of Standalone Version Key in GBFS JSON

### ISSUE THREAD

**Issue by eambele-lyft** [MobilityData/gbfs#504]
### **Have you read our [FAQ](https://gbfs.mobilitydata.org/faq)? It’s possible your question can be answered there!**
yes
### **If you are new to the specification, please introduce yourself (name and organization/link to GBFS). It’s helpful to know who we're chatting with!** 
TBS City Partnerships
### **What is the issue and _why_ is it an issue?**
We are currently experiencing an issue with the GBFS JSON file (gbfs_version.json) where we're not sure about the purpose of the "version" key. This JSON file contains two types of versions: one as a standalone key and the other as a group of keys within the "versions" block.

To illustrate, take a look at this example JSON file located at https://github.com/MobilityData/gbfs/blob/v2.3/gbfs.md#gbfs_versionsjson. We need help understanding the purpose of the standalone "version" key. Is it intended to represent the version of data the user is currently viewing, or does it represent the highest version available to the user?

Additionally, we would like to know how this standalone "version" key differs from the "version" key within the "versions" block. Here's an example snippet from the JSON file:

We appreciate any insights you can provide on this matter and in this ticket and the docs.

### **Please describe some potential solutions you have considered (even if they aren’t related to GBFS).**
Specify what each "version" key is for
### **Is your potential solution a breaking change?**
- [ ] Yes 
- [ ] No
- [X] Unsure

@Arashmansouri

**Comment by josee-sabourin** [comment]
Hi Emmanuel! Thanks for reaching out. 

The standalone version key represents the version of the current dataset. Presumably you've arrived at the `gbfs_versions.json` endpoint from a `gbfs.json` endpoint, everything under that `gbfs.json` endpoint will be, in this example, v2.3. If you needed a different version, you would go look in `gbfs_versions.json` to find `gbfs.json` URL of the version you need. 

Hope this helps!

<img width="535" alt="Screenshot 2023-04-19 at 2 24 03 PM" src="https://user-images.githubusercontent.com/66266820/233166742-107fe3f2-4b91-44e8-9be0-95d5027f8303.png">

**Comment by eambele-lyft** [comment]
If I access the gbfs_versions.json endpoint from a gbfs.json (v2.0) endpoint, what will the standalone version in the JSON represent? Will it be 2.0, or will it depend on some other scenario? Furthermore, under what circumstances would the JSON have the structure shown below, where the standalone version is 2.0 and there is a corresponding entry in the versions list with the same value?

```
{
  "last_updated": 1640887163,
  "ttl": 0,
  "version": "2.0",
  "data": {
    "versions": [
      {
        "version": "2.0",
        "url": "https://www.example.com/w"
      },
      {
        "version": "2.3",
        "url": "https://www.example.com/k"
      }
    ]
  }
}

```

**Comment by josee-sabourin** [comment]
Correct, if you access `gbfs_versions.json` from a v2.0 `gbfs.json` endpoint, the standalone version will be v2.0, there is no scenario in which this will differ (if it does it is an error, however I have never seen this happen before). 

The "active" version, in this case v2.0, will always appear in the version list for two reasons: 
- it is easier to include all of them, rather than omitting each "active" version per version. It is less maintenance on the operator
- it gives the consumer a holistic view of all available versions at all times.
