### ISSUE TITLE
Schema not matching specification in geofencing_zones

### ISSUE THREAD

**Issue by kulovan** [MobilityData/gbfs#515]
### **What is the issue and _why_ is it an issue?**

Hello 👋🏻 ,

We are working on the 3.0 update and we discovered a minor issue in the type definitions.
We are generating data types from the JSON schemas, that's why we discovered the inconsistency.

Rules in `geofencing_zones.json` which represent default rules are named `global_rules` in the specification, but `rules` i[n the schema](https://github.com/MobilityData/gbfs-json-schema/blob/2b6ad1ec46824413bbf477c556744e99991f814c/v3.0-RC/geofencing_zones.json#L159).

We are taking the specification as the source of truth by default, but we just wanted to let you know maybe it helps. :)

Best,
Dániel

**Comment by PierrickP** [comment]
Hello,
@tdelmas has worked on a PR https://github.com/MobilityData/gbfs-json-schema/pull/85 that corrects the `rules`/`global_rules `error

**Comment by richfab** [comment]
Fixed by https://github.com/MobilityData/gbfs-json-schema/pull/85
