### ISSUE TITLE
Atlanta, GA APIs

### ISSUE THREAD

**Issue by RaminaJ** [MobilityData/gbfs#516]
I am trying to access any of the vendors for Atlanta, GA and none of them works.

**Comment by mplsmitch** [comment]
@RaminaJ  Spin has pulled out of Atlanta. Relay Bikeshare is operated by Hopr and they changed platforms which may be why their feed listed in systems.csv is not working. You should contact them and see if you can get an updated URL. If that works you could open a PR to correct the one in systems.csv 
hello@hopr.com
customer service  833-838-8300

 As far as I know the only other active operators in Atlanta are now Lime and Bird. Generally speaking, these operators only publish GBFS data in cities where it's required.  Unfortunately Atlanta's current regulations don't require a public GBFS api. 

[Atlanta Regulations](https://www.atlantaga.gov/home/showpublisheddocument/50629/637532367525500000)

I would recommend you contact the city and let them know you'd like access to this data 
mobility@atlantaga.gov

**Comment by richfab** [comment]
Closing this issue as it was answered. Feel free to reopen it if needed. Thank you!
