### ISSUE TITLE
gbfs/systems.csv URL typo correction request

### ISSUE THREAD

**Issue by sabkrr777** [MobilityData/gbfs#524]
### **If you are new to the specification, please introduce yourself (name and organization/link to GBFS). It’s helpful to know who we're chatting with!** 

---LINK(superpedestrian)_dallas --employee

### **What is the issue and _why_ is it an issue?**

---URL is "https:www.link.city" *missing"//" --should be "https://www.link.city"

### **Please describe some potential solutions you have considered (even if they aren’t related to GBFS).**

---adding "//"

### **Is your potential solution a breaking change?**
- [ ] Yes 
- [ ] No
- [ X] Unsure

i am new to contributing or being involved with github.com I have some limited knowledge but I'm a quick learner just need some directions on fixing errors. I'm trying to add data to arcgis.com But I am unable to do so And I noticed to be URL is missing "//" And I need to know how I can go about getting The URL fixed As I believe this may be the problem. Would this prevent the validation Because currently it says it is unable to do so. If I fix the URL would that allow me to validate and Add data to a map for visualization?

![Screenshot 2023-07-24 11 03 43 AM](https://github.com/MobilityData/gbfs/assets/140427675/d2a665f8-c57e-4f40-891d-49f56ce47426)

**Comment by mplsmitch** [comment]
I've opened a PR in #525 with the correction. I don't know if this is what's causing your issue in ARC. You could download the data, make the correction and use it locally if you're in a hurry.

**Comment by richfab** [comment]
Hi @sabkrr777, welcome! Thank you for your question.
>If I fix the URL would that allow me to validate

If you are referring to the [gbfs-validator](https://gbfs-validator.mobilitydata.org/validator?url=https%3A%2F%2Fmds.linkyour.city%2Fgbfs%2Fus_tx_dallas%2Fgbfs.json), it is currently unable to validate or visualize Link feeds, unfortunately. 

Indeed, according to https://github.com/MobilityData/gbfs-validator/issues/90, Link's server blocks the default Got User-Agent.

**Comment by richfab** [comment]
Fixed by https://github.com/MobilityData/gbfs/pull/525
