### ISSUE TITLE
"write" access

### ISSUE THREAD

**Issue by nekromoff** [MobilityData/gbfs#53]
The GBFS currently offers read-only access to the existing system status data. Have you considered adding generic API for "write" access, e.g. to allow opening bikeshare system for rentals coming from "outside"?

I would envision this as set of general rules that system could set to either allow or don't allow rental queries coming from third-parties (apps, websites such as spinlister etc.).

**Comment by afischer** [comment]
GBFS aims to be the open data standard for bike sharing, much like [GTFS](https://en.wikipedia.org/wiki/General_Transit_Feed_Specification) does for public transportation. GBFS's goal is to provide a common way to parse the data necessary apps to display and incorporate bike share data into a project.

Hooks into a bike share provider's APIs for renting/mutating data server side falls outside of this scope. While I agree it would be nice to have an API standard for bike rentals/etc, I would argue a project of that scope would have to be separate from the GBFS standard.
