### ISSUE TITLE
Why not adding "cargo bikes" and "electric cargo bikes" to vehicle's general form factor

### ISSUE THREAD

**Issue by isabellvmz** [MobilityData/gbfs#534]
### **Have you read our [FAQ](https://gbfs.mobilitydata.org/faq)? It’s possible your question can be answered there!**
yes 

### **If you are new to the specification, please introduce yourself (name and organization/link to GBFS). It’s helpful to know who we're chatting with!** 
I´m working for a company developing mobility apps for cities.

### **What is the issue and _why_ is it an issue?**
I think we should add new vehicle's general form factor "cargo bikes" and "electric cargo bikes"
At the moment there is no category fit to it but "other".

### **Please describe some potential solutions you have considered (even if they aren’t related to GBFS).**
Adding "cargo bikes" and "electric cargo bikes" to vehicle's general form factor.

### **Is your potential solution a breaking change?**
- [ ] Yes 
- [ ] No
- [x] Unsure

**Comment by josee-sabourin** [comment]
Hi Isabell! Welcome! 

1. Adding rental bicycle. 
GBFS is designed to display shared vehicles available for rent, so by default, all vehicles are rentable. Please let me know if I am misunderstanding what you mean by rental bicycle. 

2. Adding cargo bike. 
We added cargo bike in version 2.3. See image below 
<img width="1014" alt="Screenshot 2023-08-29 at 7 52 01 AM" src="https://github.com/MobilityData/gbfs/assets/66266820/e37a51d3-3738-4bf7-8015-f4f70f488098">


3. Electric cargo bikes
Vehicle propulsions are able to be described in using the `propulsion_type` field in the `vehicle_types.json` file. See image below
<img width="1011" alt="Screenshot 2023-08-29 at 7 57 20 AM" src="https://github.com/MobilityData/gbfs/assets/66266820/65687aff-db6c-4b43-a1cf-fa59c4774e3b">


An example of what a very simple `vehicle_types.json` file could look like to represent an Electric Cargo Bike would be: 
```
{
  "last_updated": 1640887163,
  "ttl": 0,
  "version": "3.0-RC",
  "data": {
    "vehicle_types": [
      {
        "vehicle_type_id": "cargo123",
        "form_factor": "cargo_bicycle",
        "propulsion_type": "electric",
        "name": [
          {
            "text": "Example Cargo Bike",
            "language": "en"
          }
        ],          
        "wheel_count": 3,
        "default_reserve_time": 30,
        "return_constraint": "roundtrip_station",
        "default_pricing_plan_id": "cargo_plan_1",
      }
    ]
  }
}
``` 

Please let me know if you have any other questions!

**Comment by richfab** [comment]
I am closing this issue but feel free to reopen it if you have any other questions about form factors. Thank you!
