### ISSUE TITLE
GBFS ID type definition

### ISSUE THREAD

**Issue by tdelmas** [MobilityData/gbfs#541]
### **What is the issue and _why_ is it an issue?**

The current definition of `ID` in https://github.com/MobilityData/gbfs/blob/master/gbfs.md#field-types is:
- "a string" that "MUST NOT contain spaces"

This definition is the same since the first draft in 2016 https://github.com/MobilityData/gbfs/pull/5 :
> must not contain spaces

There are multiple problems with that definition: 
- A precision problem: What is a space? It's not defined here, and as any character that JSON can encode is valid, the definition is not straightforward:
  - is it `0x20` (ASCII space)
  - is it any Unicode whitespace? (https://en.wikipedia.org/wiki/Whitespace_character)
  - What about tabulation and other Unicode control characters? https://en.wikipedia.org/wiki/List_of_Unicode_characters#Control_codes

- A purpose problem: Why spaces are forbidden? What was the goal?

- The fact that allowing any characters (except spaces) may cause compatibility problems:
  - Extended Unicode characters needs to be represented differently in JSON, with two escaped character `\uXXXX\uXXXX`
  - Two different code point sequences may represent the same thing depending on the encoding path, and may need normalization to compare them  (https://en.wikipedia.org/wiki/Unicode_equivalence)
  - Non-ASCII characters may cause compatibility problem during transport and storage
  - Manual debugging for producers and integrators may be harder (hard to read, write, copy without errors)

### Current usage of IDs (based on `system.cvs`)

Of the 826 system declared, I've analyzed 798 (others are dead or broken)

IDs from `free_bike_status`, `station_status`, `vehicle_types` and `system_pricing_plans` were analyzed.

The IDs of those systems are composed of:

- `.` (dot) for 1 system (`sharedmobility.ch`)
- `@` (AT) for HelBiz 2 systems (`"bike_id"` like `"P8S0C2149C0011@SD02"` in https://gbfs.helbiz.com/v2.2/miamilakes/free_bike_status.json)
- ` ` (space !!!) for 7 systems (mostly in vehicles types)
  - 5 `publicbikesystem.net` in `vehicle_type` (ex. : `"vehicle_type_id": "E Scooter"`)
  - `openov.nl` in `station_information` (one station has the id `"GR002 "`, which is probably an error as all other station follow the same pattern without space in https://gbfs.openov.nl/ovfiets/station_information.json)
  - `sharedmobility.ch` in `plan_id` such as `emobility:83106 return"` and `emobility:2306 oneway`
- `:` for 34 systems (`sharedmobility.ch` and `entur`)
- All other systems only use `0-9`, `a-z`, `A-Z`, `-` and `_`

### **Please describe some potential solutions you have considered (even if they aren’t related to GBFS).**

The specification should clearly state what constitute a valid ID. Some solutions are presented below:

- Any Unicode character
  - Advantages: least restrictive
  - Drawbacks: comparison, encoding and compatibility issues
- Any Unicode character expects a specific list (Spaces? Non-printable characters?)
  - Advantages: most compatible with the current specification
  - Drawbacks: comparison, encoding and compatibility issues
- Any printable ASCII character (https://en.wikipedia.org/wiki/ASCII#Printable_characters)
  - Advantages: high compatibility
  - Drawbacks: a few escaping issues, restrictive compared to the current specification
- A restricted list of printable ASCII character
  - Advantages: high compatibility
  - Drawbacks: a few escaping issues, restrictive compared to the current specification
- `[A-Z][a-z][0-9]_-.:@`
  - Advantages: very high compatibility (791/798 : 99.1%, not 100% because it excludes the 7 that are using spaces)
  - Drawbacks: restrictive compared to the current specification
- `[A-Z][a-z][0-9]_-:` (789/798 : 98.8%)
  - Advantages: high compatibility, no encoding or escaping issue
  - Drawbacks: restrictive compared to the current specification
- `[A-Z][a-z][0-9]_-` (756/798: 94.7%)
  - Advantages: high compatibility, no encoding or escaping issue
  - Drawbacks: restrictive compared to the current specification

As 3.0 is a major breaking version, it is the perfect moment to restrict the character range of IDs.
Restricting them to the strictest proposition `[A-Z][a-z][0-9]_-` seams to be a reasonable choice:
  - It makes it simpler to store, transmit and compare IDs without any compatibility problem
  - They could be used in URIs without any issues (both web and Apps)
  - Systems with non-compatible IDs could simply encoded them in Base64url to be compatible
A least restrictive choice, regarding current usage, could be `[A-Z][a-z][0-9]_-.:@` or something in between. (`:` and `@` are mostly safe in most situation, but may be interpreted differently in URIs).

### Comparisons with IDs in other systems:
- In GTFS: 
https://gtfs.org/schedule/reference/
> ID - [...] is a sequence of any UTF-8 characters. Using only printable ASCII characters is recommended. [...]

- RFC 7946: The GeoJSON Format
https://datatracker.ietf.org/doc/html/rfc7946#appendix-B.1
> A Feature object's "id" member is a string or number

- HTML IDs
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id
> Technically, the value for an id attribute may contain any character, except [whitespace](https://developer.mozilla.org/en-US/docs/Glossary/Whitespace) characters. However, to avoid inadvertent errors, only [ASCII](https://developer.mozilla.org/en-US/docs/Glossary/ASCII) letters, digits, '_', and '-' should be used, and the value for an id attribute should start with a letter.

### References:
- JSON strings: https://datatracker.ietf.org/doc/html/rfc8259#section-7
> All Unicode characters may be placed within the
   quotation marks, except for the characters that MUST be escaped:
   quotation mark, reverse solidus, and the control characters (U+0000
   through U+001F).

- https://fr.wikipedia.org/wiki/Base64#base64url
Base64 encoding require `[a-z][0-9]+/=`
Base64url require `[a-z][0-9]_-`

### **Is your potential solution a breaking change?**
- [x] Yes

**Comment by testower** [comment]
Just to explain Entur's usage of `:`. We have adopted the transmodel/netex ID convention for data separation purposes with 
 the format `[codespace]:[type]:[identification]`. We would favor a solution that continues to allow `:` in IDs for this reason.

See https://enturas.atlassian.net/wiki/spaces/PUBLIC/pages/728563782/General+information+NeTEx#Definitions and https://enturas.atlassian.net/wiki/spaces/PUBLIC/pages/1883439205/Mobility+Data+Collection+-+GBFS+v2.2-v2.3#IDs

**Comment by richfab** [comment]
Thank you @tdelmas for the thorough analysis of the known feeds and for the detailed suggestions!
I am curious to know what other GBFS producers and consumers think about this. If anyone has a preferred solution, feel free to participate in the discussion!

**Comment by josee-sabourin** [comment]
Closing this thread since a PR has been opened for this at #545, please continue the discussion there!
