### ISSUE TITLE
Donkey Republic URL for Barcelona in systems.csv is returning 404

### ISSUE THREAD

**Issue by GerdC** [MobilityData/gbfs#597]
Donkey Republic URL for Barcelona in systems.csv is returning 404

Broken URL:
https://stables.donkey.bike/api/public/gbfs/2/donkey_barcelona/gbfs.json

Donkey republic has its own systems.csv:
https://github.com/DonkeyRepublic/donkey_gbfs/blob/master/systems_v2.csv
This contains a different url for Barcelona, that is also broken.
I opened an issue there also: https://github.com/DonkeyRepublic/donkey_gbfs/issues/5

### Is your potential solution a breaking change?
- [ ] Yes 
- [X] No
- [ ] Unsure
it is already broken

**Comment by richfab** [comment]
Hi @GerdC and welcome!
I'm the Product Manager for Shared Mobility at MobilityData.
Thank you for opening this issue and for sharing Donkey Republic catalog. I did not know about it 🙌 
Best,
Fabien

**Comment by richfab** [comment]
Tagging @trojkac for visibility.

**Comment by GerdC** [comment]
'Due to legal reasons', Donkey republic closed the Barcelona feed  https://github.com/DonkeyRepublic/donkey_gbfs/issues/5#issuecomment-1944037506
