### ISSUE TITLE
 Use OSM opening hours format?

### ISSUE THREAD

**Issue by fkh** [MobilityData/gbfs#6]
Are we trying to invent a new format for hours of operation (system_hours.json)? 

What about a format that is already used and supported with code libraries—see OSM’s opening_hours (http://wiki.openstreetmap.org/wiki/Key:opening_hours)

**Comment by mdarveau** [comment]
If we are to do one last breaking change because of https://github.com/NABSA/gbfs/issues/10 and https://github.com/NABSA/gbfs/issues/9, I'd be +1 on this one. It seems more flexible while keeping things simple for producers and consumers.

**Comment by jcn** [comment]
The OSM format looks flexible, but also requires a lot more parsing than the explicit (but admittedly not as flexible) format that we defined in the spec. I'd be concerned with this significant of a change without much more discussion. Specifically, I'd be curious as to how using the OSM format would affect consumers - it seems much more brittle to me.

For reference, the current definition is here: https://github.com/NABSA/gbfs/blob/master/gbfs.md#system_hoursjson

**Comment by Empty2k12** [comment]
Good objection by @jcn. By using OSM data, we would also lose info about member and non-member opening times, unless we changed the spec to something like

Field Name        | Required  | Defines
------------------| --------- | ----------
rental_hours          | Yes       | Object containing opening hours
\- rental_hours      | Yes       | OSM format rental hours for members of the system. If `rental_hours_non_member` is not specified, there are no differing hours for members and non-members
\- rental_hours_non_member      | No       | OSM format rental hours for non-members

I can also see the clear advantage of using the same libraries for parsing the date as OSM dates which the developer of an application might already be using for parsing opening hours from OSM itself.

How could we support differing opening hours for a special event like holidays or strikes? Make that part of system alerts?
Additionally, I can think of one instance of an opening-hour restricted station in our city, which offers a comment with the opening hours, asking users to ring and they will be permitted access to the station. How can such comments be encoded with an opening hour?

**Comment by mplsmitch** [comment]
We have a proposal to change the format for operation dates and times to OSM Opening Hours format. Since this would be a breaking change it would happen with v3.0. This is a significant revision to the specification so we'd like to get some feedback before it goes to a PR. I've written up the proposal in [this document](https://docs.google.com/document/d/1FN_7FnyqqK7g6unN70fqlMMhE3THIoM0jN_AlmSR4VY/edit?usp=sharing). Please comment along with your willingness to implement.

**Comment by mplsmitch** [comment]
Closing this - ongoing discussion of OSM Opening Hours has been moved to #289
