### ISSUE TITLE
German nextbike URLs lead to 404 error

### ISSUE THREAD

**Issue by Henry00572** [MobilityData/gbfs#608]
### Have you read our [FAQ](https://gbfs.mobilitydata.org/faq)? It’s possible your question can be answered there!
The FAQ link also leads to a 404... [This url](https://gbfs.org/learn/faq/) works and I have read it.

### If you are new to the specification, please introduce yourself (name and organization/link to GBFS). It’s helpful to know who we're chatting with!
I'm Hendrik from Düsseldorf, active contributor in the [OpenStreetMap](https://www.openstreetmap.org) project.

### What is the issue and _why_ is it an issue?
The URLs of German Nextbike systems in systems.csv lead to 404 errors. The Auto-Discovery URL still works, but it would be nice if both worked. The expected target page would explain bikesharing, link to the Nextbike app and show location-specific information.

### Please describe some potential solutions you have considered (even if they aren’t related to GBFS).
The affected URLs have the form `https://www.nextbike.de/de/<locationname>/`. The part `/de` has to be removed, so that `https://www.nextbike.de/<locationname>/` works, redirecting to `https://www.nextbike.de/<locationname>/de`.

### Is your potential solution a breaking change?
- [ ] Yes 
- [X] No
- [ ] Unsure

**Comment by richfab** [comment]
Hi @Henry00572 and welcome 👋 

Thank you very much for raising this issue. It was fixed in https://github.com/MobilityData/gbfs/pull/610.

If you haven't already, you may be interested in joining the #gbfs public channel on MobilityData Slack: https://share.mobilitydata.org/slack.

Best regards,
Fabien
