### ISSUE TITLE
Show supported GBFS versions in systems.csv

### ISSUE THREAD

**Issue by richfab** [MobilityData/gbfs#659]
### User Problem
As a GBFS consumer, I would like to know which feeds support a given GBFS version.

### Proposed solution
Add a column ‘Supported Versions’ to [systems.csv](https://github.com/MobilityData/gbfs/blob/master/systems.csv) with the GBFS versions supported by any given feed:

<img width="1342" alt="image" src="https://github.com/user-attachments/assets/c3ee00f7-05b3-4bf2-998c-5c6ac37c414c">

#### How to extract the supported versions
Extracting the supported versions should be needed only to fill the systems.csv file initially. Then, when new feeds are added to the catalog, we can manually look for the supported versions in the gbfs_versions file and add it to the column.

What is needed from the MobilityData's dev team:

Write a script that will go through every line and:
1. Open the file from the ‘Auto-Discovery URL’ column (we’ll use the [first feed](https://dubai.publicbikesystem.net/customer/gbfs/v2/gbfs.json) of systems.csv as an example in the steps below).
1. If the property ‘version’ exists in the file, add it to the list of ‘Supported Versions’.
![image](https://github.com/MobilityData/gbfs/assets/2423604/f1c27868-b2b5-4466-a77a-b8e66e2b7983)
Else, add ‘1.0’ to the list of ‘Supported Versions’ and go to the next line in the csv file.
1. If the value ‘gbfs_versions’ exists in the list of feeds from the auto-discover file:
![image](https://github.com/MobilityData/gbfs/assets/2423604/aef65d06-8a6f-42b5-a1f0-391a93469328)
Open the corresponding file from the property ‘url’.
Add every value from the properties ‘version’ to the list of ‘Supported Versions’.
![image](https://github.com/MobilityData/gbfs/assets/2423604/a2778bcf-b070-4492-a29d-fae81dfe7d45)
1. Remove the duplicates from the list of ‘Supported Versions’ and sort the versions by ascending order. For example: “1.0 ; 1.1 ; 2.3 ; 3.0 ; 3.0-RC”.
The separator should be a semi-colon surrounded with 1 space on each side for readability (“ ; “).

**Comment by mplsmitch** [comment]
@richfab maybe consider adding a step where you ping each version for an http response so you can validate the urls for older versions and not add any that return 404s etc

**Comment by richfab** [comment]
Thanks @mplsmitch, that's a great suggestion.

However, I think in this first iteration it is better to just trust what is declared in the `gbfs_versions` file by the producer. Indeed, an older version which returns a 404 when running the script could become available again a few days later and then it would not be listed in the supported versions.

But I am taking note of this idea for when we will have a dynamic database of GBFS feeds with which we can ping the feeds regularly and indicate their status (availability, compliance, files filled in, etc.).
