### ISSUE TITLE
Mismatch privacy_last_updated and terms_last_updated REQUIRED vs corresponding urls OPTIONAL

### ISSUE THREAD

**Issue by hbruch** [MobilityData/gbfs#677]
### What is the issue and _why_ is it an issue?
With GBFSv3.0, `privacy_last_updated` and `terms_last_updated` became REQUIRED (in v2.3 they were CONDITIONALLY REQUIRED, in case `privacy_url`/`terms_url` are provided.
The change apparently was introduced with https://github.com/MobilityData/gbfs/commit/212386e2d3c432f9ceaefced37fd75e0ab3b0dce but I see no comment explaining the rational behind it.

### Please describe some potential solutions you have considered (even if they aren’t related to GBFS).
IMHO this is is inconsistent and 
* either the `*_updated` properties should be reverted to `CONDITIONALLY REQUIRED` 
* or `terms_url` and `privacy_url` become `REQUIRED` as well.

### Is your potential solution a breaking change?
- [X] Yes 
- [ ] No
- [ ] Unsure

**Comment by tdelmas** [comment]
I confirm that it was NOT the intention of the commit. This is in my opinion now a bug in the specification and we should revert those two lines.
