### ISSUE TITLE
Additional address fields for station_information.json

### ISSUE THREAD

**Issue by fkh** [MobilityData/gbfs#7]
`station_information.json` schema could be enhanced by providing additional address fields (could be still optional)
- location description
- lat/long calculation method (from geocoding an address using <service name>; manual placement using <map> as a reference; using a GPS receiver … etc.)
- station photo URL(s).

**Comment by fruminator** [comment]
@fkh can we please have the original suggestor of these explain the use case?  Not too hard to imagine why you might want a photo, but why does the method of geocoding matter?  What does location description mean?

**Comment by heidiguenin** [comment]
@fkh  Is this still a conversation you want to keep open? If it's no longer relevant, I'm going to go ahead and close this issue, but if that's not the case, could you share your thoughts on those questions from @fruminator ? Thanks!
