### ISSUE TITLE
gbfs-validator.mobilitydata.org

### ISSUE THREAD

**Issue by Lucerberus** [MobilityData/gbfs#706]
### What is the issue and _why_ is it an issue?
        There are some gbfs that do not validate
![Image](https://github.com/user-attachments/assets/92d6e7cb-7db6-42b1-a66c-ae34122fd712)
![Image](https://github.com/user-attachments/assets/c02da648-e47e-4f4d-b29b-81f30b8df8e5)

### Please describe some potential solutions you have considered (even if they aren’t related to GBFS).
       update gbfs/systems.csv
### Is your potential solution a breaking change?
- [ ] Yes 
- [ x] No
- [ ] Unsure

**Comment by mplsmitch** [comment]
You're using the wrong URL - you should be using the discovery file listed in systems.csv ( gbfs.json), for example: 


https://gbfs.helbiz.com/v2.2/palermo/gbfs.json

**Comment by Lucerberus** [comment]
the problem is that in the case of helbiz version 2.2 contains incorrect data, which does not coincide with their application,I also used gbfs of Link(superpedestrian) in the first screenshot and it doesn’t work(https://mds.linkyour.city/gbfs/2.2/it_palermo/free_bike_status.json)

**Comment by mplsmitch** [comment]
On the Helbiz data, you'll need to contact Helbiz.  On the Supedestrian feed, as I said you are using the wrong link in the validator. You have to use the discovery file:  **https://mds.linkyour.city/gbfs/2.2/it_palermo/gbfs.json**  not  **/free_bike_status.json**.



![Image](https://github.com/user-attachments/assets/a5e59502-8f82-45bd-884d-edc9e369642a)

**Comment by richfab** [comment]
Marking this issue as resolved 👍
