### ISSUE TITLE
Curtin University Bike Share Not Resolving

### ISSUE THREAD

**Issue by tague** [MobilityData/gbfs#74]
The Curtin University Bike Share and associated feeds no longer resolve.  I'm not affiliated with them so I can't speak authoritatively about what is going on.

**Comment by jcn** [comment]
I can find very little info about this bike share scheme, but it does seem like it was shut down:

https://www.change.org/p/curtin-university-guild-reinstate-bike-share-at-bentley-campus-curtin-university
