### ISSUE TITLE
where can I find the historical station_status.json ?

### ISSUE THREAD

**Issue by lhyfst** [MobilityData/gbfs#83]
thanks in advance!

**Comment by mplsmitch** [comment]
From the introduction: 
"This specification has been designed with the following concepts in mind:

Provide the status of the system at this moment

Do not provide information whose primary purpose is historical"

**Comment by lhyfst** [comment]
em...I just want to do my research

**Comment by jcn** [comment]
@lhyfst There are a number of public datasets out there from people who have been collecting this data over time specifically for people to do research off of, but this is not part of the GBFS spec. 

This other thread might be helpful to you: https://github.com/NABSA/gbfs/issues/47#issuecomment-242412688

**Comment by lhyfst** [comment]
Thank you very much.I have looked through the web pages. Unfortunately, I do not find the data I want.
Please re-open this issue ,I need more help.

**Comment by jcn** [comment]
Which systems are you looking for information on specifically?

**Comment by lhyfst** [comment]
Citibike system and Capital Bikeshare system.
I'm studying how to predict over-demand stations and how to design rebalance plan.
So, historical station status data is necessary for me.
Thanks!

**Comment by jcn** [comment]
For Citi Bike and Capital Bikeshare, check out:

* https://www.citibikenyc.com/system-data
* https://www.capitalbikeshare.com/system-data

**Comment by mplsmitch** [comment]
historical status data is difficult to come by unless you can find someone who's been logging it - here's an example:  http://www.cabitracker.com/status_history.php
If your timeline allows you might just start capturing ans storing the station_status.json feeds for a few weeks

**Comment by lhyfst** [comment]
Thanks,everybody!
I have found an interesting data set https://www.theopenbus.com/raw-data.html
Although this data set does not seem to be complete,this is the only one I have found that I truly need.
If anybody have a more complete data set,hope you can share it with everyone here

**Comment by nackko** [comment]
Some historical data here
https://drive.google.com/folderview?id=0BzRoZlJR-XPLOU5qYm1JX0NEYlk
