### ISSUE TITLE
data

### ISSUE THREAD

**Issue by sankalpsg** [MobilityData/gbfs#87]
where can i get data for damaged bike ids or bike id which required repairs

**Comment by barbeau** [comment]
See `station_status.num_bikes_disabled` and `num_docks_disabled` (https://github.com/NABSA/gbfs/blob/master/gbfs.md#station_statusjson):

>* num_bikes_disabled - Number of disabled bikes at the station. Vendors who do not want to publicize the number of disabled bikes or docks in their system can opt to omit station capacity (in station_information), num_bikes_disabled and num_docks_disabled. If station capacity is published then broken docks/bikes can be inferred (though not specifically whether the decreased capacity is a broken bike or dock)
>* num_docks_disabled - Number of empty but disabled dock points at the station. This value remains as part of the spec as it is possibly useful during development

...and `free_bike_status.is_disabled` (https://github.com/NABSA/gbfs/blob/master/gbfs.md#free_bike_statusjson):

>* is_disabled - 1/0 value - is the bike currently disabled (broken)
