### ISSUE TITLE
Points or incentives system for stations and free bikes

### ISSUE THREAD

**Issue by yuzawa-san** [MobilityData/gbfs#91]
I am most familiar with the Citibike NYC's (Motivate) BikeAngels program which associates points with picking up or dropping off bikes at stations. https://bikeangels.citibikenyc.com/ They offer membership extensions and other perks for members who accumulate points. I do not know of other systems which offer incentives for dropping off or picking up, but perhaps you all may know. Currently my application hits the Citibike GBFS feed and makes a subsequent request to their bike angels api. However in recent days it appears they may have merged their status and bike angels info into the same api endpoint: https://layer.bicyclesharing.net/map/v1/nyc/stations See fields like `"bike_angels_action": "give", "bike_angels_points": 1`

*Proposal*: Add optional fields to the inner objects within `station_status.json` and `free_bike_status.json`:

Field Name        | Required  | Defines
------------------| --------- | ----------
incentive_status          | Optional       | Enumerable string value: `NEUTRAL`, `TAKE`, `GIVE`
incentive_value            | Optional       | Integer: number of points, assuming a points based system is being used

It makes sense that `incentive_status` could be set on its own without an `incentive_value` in cases where there is not a value based system. These fields should only be used if there is an actual incentive system in place. I would not like the `incentive_status` field just being set using a simple algorithm with rules like `bikes/docks > 0.95` and so on.

It may also be possible to add those fields to the zones from https://github.com/NABSA/gbfs/issues/65 as well.

**Comment by yuzawa-san** [comment]
@afischer @fkh

**Comment by mvs202** [comment]
We could also add two new fields for "bike angel" programs for station_status.json(https://github.com/NABSA/gbfs/blob/master/gbfs.md#station_statusjson)

bikein_points: incentive points for bringing a bike to the station (default 0) 
bikeout_points: incentive points for bringing a bike to the station (default 0) 

-with the assumption only one can be non-zero.

**Comment by mplsmitch** [comment]
Is anyone interested in revisiting this idea? It seems like it could have additional value now that an incentive could be tied to a GeoFence zone.
