### ISSUE TITLE
Vetting of PR #92, V1.1 before merge

### ISSUE THREAD

**Issue by mplsmitch** [MobilityData/gbfs#93]
Hey everybody, 
We have an open PR, #92  from @dsgermain that I would like to move forward on but there hasn't been any discussion since it was submitted. This is a significant update and I'd like others in the group to weigh in before it gets merged.  If no outstanding issues are identified after one week’s time, and there is general agreement that the change is worthwhile and follows the GBFS guiding principles outlined in the READ.ME I will go ahead with the merge on 3/23/2018.

Thanks

**Comment by barbeau** [comment]
Just a question on the [official change process](https://github.com/NABSA/gbfs#overview-of-the-change-process) - it currently says:
>...
>3. Find at least one GBFS producer to implement and test the proposed change.
>...

I've interpreted this to be the same as the GTFS change process, which requires that the proposal actually be implemented before it can be officially adopted.  The following section ["Extensions Outside of the Specification"](https://github.com/NABSA/gbfs#extensions-outside-of-the-specification) says:
>To accommodate the needs of feed producers and consumers prior to the adoption of a change, additional fields can be added to feeds even if these fields are not part of the official specification.

...which also implies that implementation comes before adoption.

Is the above saying that the PR https://github.com/NABSA/gbfs/pull/92 will be adopted before implementation?

**Comment by serialc** [comment]
I wonder if some other issues should not be integrated into V1.1, specifically https://github.com/NABSA/gbfs/issues/15, making implementation less risky to test/deploy.

Perhaps easier agreed upon minor changes for [milestone 2.0](https://github.com/NABSA/gbfs/milestone/1) could also be integrated: https://github.com/NABSA/gbfs/issues/6, https://github.com/NABSA/gbfs/issues/9 and https://github.com/NABSA/gbfs/issues/10.

**Comment by mplsmitch** [comment]
@barbeau You make a good point. My thinking was that since @dsgermain is implementing the proposed changes in his feeds, this was covered but you're right, the work hasn't happened yet.  What do you think is a reasonable time frame for testing before a something gets merged?

@serialc on #15 I agree this would be a good time to include it. Versioning seems like a prerequisite to the breaking changes in #6, #9 and #10.

**Comment by barbeau** [comment]
>What do you think is a reasonable time frame for testing before a something gets merged?

The requirements for GTFS include a producer and consumer implementation to ensure that the proposed field actually works in the real world.  I'd say ideally we'd have the same thing here - someone producing and consuming the new data in at least a development environment to make sure there aren't any unforeseen issues.

**Comment by dsgermain** [comment]
OK, not an issue. Our mobile app will be the first consumer of this information. I'll ping back when it is live.

**Comment by nackko** [comment]
Can both implementations be provided by the same party ? I'm no expert in
standards governance so maybe my point is moot.

**Comment by barbeau** [comment]
In GTFS, no, it has to be two parties to adopt a new field.

**Comment by nackko** [comment]
Did anyone ever bothered reaching out to @eskerda and/or considered implementing a consumption proposal in the citybikes API wrappers ?
https://github.com/eskerda/pybikes/tree/fe534bf4cdd395aefe90a37bbe8e7ade3361972f
https://github.com/eskerda/pybikes/blob/fe534bf4cdd395aefe90a37bbe8e7ade3361972f/pybikes/gbfs.py

[EDIT]
I realized their system still used the old XML feed in my hometown, so :
https://github.com/eskerda/pybikes/pull/313

**Comment by nackko** [comment]
@mplsmitch, I guess the discussion is still ongoing ?

**Comment by mplsmitch** [comment]
@f8full - Where we left it is that @dsgermain will go ahead and start publishing. Once we have a consumer implementation we can go ahead with merging if there are no issues. Maybe you'd like to be that consumer?

**Comment by nackko** [comment]
Ok I understand. The trouble is I don't consume directly but through
citybik.es. My level in python is not good enough to create a PR on that
project. I would gladly give a hand though.

**Comment by khwilson** [comment]
I'm guessing this conversation is about closed, but I just noticed it when I was coming to look up details of the spec. Apologies for being late to the game.

I just wanted to pop in and comment briefly on the `free_bike_status.json` change: A boolean `is_ebike` is more restrictive than an enum `bike_type`. As different types of bike-like mobility devices are coming online (I'm thinking of scooters specifically), it might be good to support them.

Anyway, perhaps this is a v2 thing. Thanks for all your work on getting this out!

**Comment by nackko** [comment]
I would add to that, in my hometown there are 3 gears bikes and 7 gears
one. Being able to distinguish in client applications would be nice.

**Comment by HeidiMG** [comment]
test:
@all-contributors please add @mplsmitch @barbeau @serialc @dsgermain @f8full @khwilson for answering this question

(Hi all! I'm with the team NABSA hired for the project @mplsmitch mentioned in #137. We'll be diving into that work with y'all soon. Right now I'm working on getting the our contributors table populated, though. So you'll see some call-outs here and there for a bit!)

**Comment by HeidiMG** [comment]
@all-contributors please add @barbeau @serialc @dsgermain @f8full @khwilson for answering this question

**Comment by heidiguenin** [comment]
PR #136 and PR #175 address these issues and represent a heap of input from GBFS consumers and producers. We're hoping we can solidify support around them as the next steps forward. It would be great to get all of your input over there on the solutions that have emerged so far as  "minimum viable proposals" that better represents what operators are providing on the ground.

That said, I'd like to propose we close this issue and move relevant conversation there.

@mplsmitch @dsgermain @barbeau @serialc @f8full @khwilson
