### ISSUE TITLE
Different rental hours per station

### ISSUE THREAD

**Issue by skinkie** [MobilityData/gbfs#98]
At this moment different rental hours per station can only be modeled if every station is modeled as a different system. Wouldn't it be more elegant to have the ability to set the rental hours per station opposed to per system?

**Comment by sven4all** [comment]
This is exactly what I want to propose next :-) . In the Netherlands we do have manned stations as well, therefor this would be a nice addition.

**Comment by jcn** [comment]
I guess the real question is whether this is the kind of information that needs to be modeled in GBFS, or whether it's something that should just be implemented on the backend and updates the actual rental status of a station as needed.

i.e. is this information that is needed ahead of time ("this station will become a manned station at 9am") or is it more important in the moment ("this station is currently online, regardless of whether it will be offline in 20 minutes")?

**Comment by sven4all** [comment]
If you know it ahead of time, what is the reason to communicate it? The actual rental status is already part of the specification, right?

Situations where this information can be handy is for trip planning (planning a trip 2 hours in the future for example, or the rental station is not opened right now but after having a train ride the rental station is already opened) , also it's useful information to see until what time you can return your bicycle.

**Comment by mplsmitch** [comment]
This sounds a similar to an old discussion we had in #16 regarding additional station data and services. I'm generally supportive although I would like to see a vendor present a specific use case so we can avoid making speculative changes.

**Comment by skinkie** [comment]
@mplsmitch what is it then what you want to see?

The specific vendor OVfiets (NL) has the following operational rules:
 - there are manned an unmanned stations
 - each stations has another operational availability (per station is not supported in GBFS)
 - the availability has calendar exceptions (not supported at all in GBFS)
 - bicycles brought back to a different station have an increased rental fee

**Comment by mplsmitch** [comment]
I'm sure we can identify many vendors with operational rules that aren't currently supported. The question is, is there a vendor who is publishing GBFS who has identified a need for additional features, or are we speculating that if we model their operational rules they will use the new features? Ideally we would get a proposal from OVfiets.

**Comment by skinkie** [comment]
Both @sven4all and me are creating a GBFS feed for OVfiets and others in The Netherlands, and have difficulties to model it. http://gbfs.openov.nl/

**Comment by mplsmitch** [comment]
Ok, I understand now - that's good enough for me. That's an impressive project -  please consider adding all of those the to the systems.csv list when you're ready. Maybe we can break down your list and start defining these one at a time starting with rental hours per station. That should help us determine if a new endpoint covering additional station services is needed as proposed in #16.

**Comment by skinkie** [comment]
I would actually would like to suggest an extension that a gbfs feedtype would exist that would refer to other gbfs feeds, instead of a CSV file ;)

**Comment by antrim** [comment]
I've heard from most GBFS consumers that they are interested in the real-time status of the system, not scheduled changes (because routing has to be done based on the real-time locations of available vehicles). Are there GBFS consumers out there who would consume scheduled hours data and implement dependent features in their apps?

A feature for valet stations has been added to this open proposal: #175.

**Comment by heidiguenin** [comment]
@skinkie @sven4all I wanted to follow up with you about the issues raised here now that the minimum viable proposals for geofencing have been adopted into v2.1RC (including valet). 

For the last three points of [your request](https://github.com/NABSA/gbfs/issues/98#issuecomment-388098755), it sounds like you will produce the data. Do you know of an interested consumer of that information?  Do you have any other recommendations about how you'd like to see these fields handled?

**Comment by mplsmitch** [comment]
Can anyone point me to examples of systems that set different hours for individual stations? I'm aware of OVfiets but looking for additional examples.

**Comment by mplsmitch** [comment]
We have a proposal to support this feature. It's done using the Open Street Map Open Hours format which would be a major revision to the specification. Because it's a breaking change it would become part of v3.0. Before it goes to a PR we'd like to encourage some feedback so I've written up the proposal in [this document](https://docs.google.com/document/d/1FN_7FnyqqK7g6unN70fqlMMhE3THIoM0jN_AlmSR4VY/edit?usp=sharing). Please comment on the proposal including your willingness to implement.
CC: @skinkie @sven4all

**Comment by mplsmitch** [comment]
Closing - ongoing discussion of different rental hours per station has been moved to #289
